### ISSUE TITLE
tasks_without_stage_dependency

### ISSUE THREAD

**Issue by troelskn** [capistrano/capistrano#1226]
Just trying out with cap `3.X`, but I get the following error when creating a simple one-task Capfile:

```
$ bundle exec cap foo --trace
cap aborted!
NameError: undefined local variable or method `tasks_without_stage_dependency' for #<Capistrano::Application:0x007fc914312fb0>
/Users/troelskn/.rvm/gems/ruby-1.9.3-p327/gems/capistrano-3.3.5/lib/capistrano/application.rb:57:in `top_level_tasks'
/Users/troelskn/.rvm/gems/ruby-1.9.3-p327/gems/rake-10.4.2/lib/rake/application.rb:106:in `block in top_level'
/Users/troelskn/.rvm/gems/ruby-1.9.3-p327/gems/rake-10.4.2/lib/rake/application.rb:115:in `run_with_threads'
/Users/troelskn/.rvm/gems/ruby-1.9.3-p327/gems/rake-10.4.2/lib/rake/application.rb:100:in `top_level'
/Users/troelskn/.rvm/gems/ruby-1.9.3-p327/gems/rake-10.4.2/lib/rake/application.rb:78:in `block in run'
/Users/troelskn/.rvm/gems/ruby-1.9.3-p327/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
/Users/troelskn/.rvm/gems/ruby-1.9.3-p327/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'
/Users/troelskn/.rvm/gems/ruby-1.9.3-p327/gems/capistrano-3.3.5/lib/capistrano/application.rb:15:in `run'
/Users/troelskn/.rvm/gems/ruby-1.9.3-p327/gems/capistrano-3.3.5/bin/cap:3:in `<top (required)>'
/Users/troelskn/.rvm/gems/ruby-1.9.3-p327/bin/cap:23:in `load'
/Users/troelskn/.rvm/gems/ruby-1.9.3-p327/bin/cap:23:in `<main>'
/Users/troelskn/.rvm/gems/ruby-1.9.3-p327/bin/ruby_noexec_wrapper:14:in `eval'
/Users/troelskn/.rvm/gems/ruby-1.9.3-p327/bin/ruby_noexec_wrapper:14:in `<main>'
```

Capfile:

```
require 'bundler'
require 'capistrano'

task :foo do
  run_locally do
    puts "hiya"
  end
end
```

What am I missing here?

**Comment by dav** [comment]
Just in case it helps someone, you can also get this error if you cleverly did a `touch Capfile` (creating an empty file) before continuing reading through docs and then running `cap install`.
