### ISSUE TITLE
Cannot deploy to server - getting Errno::EISDIR exception

### ISSUE THREAD

**Issue by kiela** [capistrano/capistrano#1231]
When I try to deploy to a server I got `Capistrano::ConnectionError` exception with message `connection failed for: dev.domain.com (Errno::EISDIR: Is a directory @ io_fread - /home/kiela/workspace/ruby/project)`. However, I can ssh to the server without any issue.
Exception backtrace looks like this:

```
[
  [ 0] "/home/kiela/.rvm/gems/ruby-2.1.5@global/gems/capistrano-2.14.1/lib/capistrano/configuration/connections.rb:134:in `establish_connections_to'",
  [ 1] "/home/kiela/.rvm/gems/ruby-2.1.5@global/gems/capistrano-2.14.1/lib/capistrano/configuration/connections.rb:188:in `block in execute_on_servers'",
  [ 2] "/home/kiela/.rvm/gems/ruby-2.1.5@global/gems/capistrano-2.14.1/lib/capistrano/configuration/connections.rb:186:in `each'",
  [ 3] "/home/kiela/.rvm/gems/ruby-2.1.5@global/gems/capistrano-2.14.1/lib/capistrano/configuration/connections.rb:186:in `each_slice'",
  [ 4] "/home/kiela/.rvm/gems/ruby-2.1.5@global/gems/capistrano-2.14.1/lib/capistrano/configuration/connections.rb:186:in `execute_on_servers'",
  [ 5] "/home/kiela/.rvm/gems/ruby-2.1.5@global/gems/capistrano-2.14.1/lib/capistrano/configuration/actions/invocation.rb:183:in `run_tree'",
  [ 6] "/home/kiela/.rvm/gems/ruby-2.1.5@global/gems/capistrano-2.14.1/lib/capistrano/configuration/actions/invocation.rb:155:in `run'",
  [ 7] "/home/kiela/.rvm/gems/ruby-2.1.5@global/gems/capistrano-2.14.1/lib/capistrano/configuration/namespaces.rb:191:in `method_missing'",
  [ 8] "/home/kiela/.rvm/gems/ruby-2.1.5@global/gems/capistrano-2.14.1/lib/capistrano/recipes/deploy.rb:247:in `block (3 levels) in load'",
  [ 9] "/home/kiela/.rvm/gems/ruby-2.1.5@global/gems/capistrano-2.14.1/lib/capistrano/configuration/execution.rb:119:in `call'",
  [10] "/home/kiela/.rvm/gems/ruby-2.1.5@global/gems/capistrano-2.14.1/lib/capistrano/configuration/execution.rb:119:in `block in rollback!'",
  [11] "/home/kiela/.rvm/gems/ruby-2.1.5@global/gems/capistrano-2.14.1/lib/capistrano/configuration/execution.rb:115:in `each'",
  [12] "/home/kiela/.rvm/gems/ruby-2.1.5@global/gems/capistrano-2.14.1/lib/capistrano/configuration/execution.rb:115:in `rollback!'",
  [13] "/home/kiela/.rvm/gems/ruby-2.1.5@global/gems/capistrano-2.14.1/lib/capistrano/configuration/execution.rb:60:in `rescue in transaction'",
  [14] "/home/kiela/.rvm/gems/ruby-2.1.5@global/gems/capistrano-2.14.1/lib/capistrano/configuration/execution.rb:64:in `transaction'",
  [15] "/home/kiela/.rvm/gems/ruby-2.1.5@global/gems/capistrano-2.14.1/lib/capistrano/configuration/namespaces.rb:191:in `method_missing'",
  [16] "/home/kiela/.rvm/gems/ruby-2.1.5@global/gems/capistrano-2.14.1/lib/capistrano/recipes/deploy.rb:228:in `block (2 levels) in load'",
  [17] "/home/kiela/.rvm/gems/ruby-2.1.5@global/gems/capistrano-2.14.1/lib/capistrano/configuration/execution.rb:140:in `instance_eval'",
  [18] "/home/kiela/.rvm/gems/ruby-2.1.5@global/gems/capistrano-2.14.1/lib/capistrano/configuration/execution.rb:140:in `invoke_task_directly'",
  [19] "/home/kiela/.rvm/gems/ruby-2.1.5@global/gems/capistrano-2.14.1/lib/capistrano/configuration/callbacks.rb:25:in `invoke_task_directly_with_callbacks'",
  [20] "/home/kiela/.rvm/gems/ruby-2.1.5@global/gems/capistrano-2.14.1/lib/capistrano/configuration/execution.rb:90:in `execute_task'",
  [21] "/home/kiela/.rvm/gems/ruby-2.1.5@global/gems/capistrano-2.14.1/lib/capistrano/configuration/namespaces.rb:191:in `method_missing'",
  [22] "/home/kiela/.rvm/gems/ruby-2.1.5@global/gems/capistrano-2.14.1/lib/capistrano/configuration/namespaces.rb:110:in `block in define_task'",
  [23] "/home/kiela/.rvm/gems/ruby-2.1.5@global/gems/capistrano-2.14.1/lib/capistrano/recipes/deploy.rb:196:in `block (2 levels) in load'",
  [24] "/home/kiela/.rvm/gems/ruby-2.1.5@global/gems/capistrano-2.14.1/lib/capistrano/configuration/execution.rb:140:in `instance_eval'",
  [25] "/home/kiela/.rvm/gems/ruby-2.1.5@global/gems/capistrano-2.14.1/lib/capistrano/configuration/execution.rb:140:in `invoke_task_directly'",
  [26] "/home/kiela/.rvm/gems/ruby-2.1.5@global/gems/capistrano-2.14.1/lib/capistrano/configuration/callbacks.rb:25:in `invoke_task_directly_with_callbacks'",
  [27] "/home/kiela/.rvm/gems/ruby-2.1.5@global/gems/capistrano-2.14.1/lib/capistrano/configuration/execution.rb:90:in `execute_task'",
  [28] "/home/kiela/.rvm/gems/ruby-2.1.5@global/gems/capistrano-2.14.1/lib/capistrano/configuration/execution.rb:102:in `find_and_execute_task'",
  [29] "/home/kiela/.rvm/gems/ruby-2.1.5@global/gems/capistrano-2.14.1/lib/capistrano/cli/execute.rb:46:in `block in execute_requested_actions'",
  [30] "/home/kiela/.rvm/gems/ruby-2.1.5@global/gems/capistrano-2.14.1/lib/capistrano/cli/execute.rb:45:in `each'",
  [31] "/home/kiela/.rvm/gems/ruby-2.1.5@global/gems/capistrano-2.14.1/lib/capistrano/cli/execute.rb:45:in `execute_requested_actions'",
  [32] "/home/kiela/.rvm/gems/ruby-2.1.5@global/gems/capistrano-2.14.1/lib/capistrano/cli/help.rb:19:in `execute_requested_actions_with_help'",
  [33] "/home/kiela/.rvm/gems/ruby-2.1.5@global/gems/capistrano-2.14.1/lib/capistrano/cli/execute.rb:34:in `execute!'",
  [34] "/home/kiela/.rvm/gems/ruby-2.1.5@global/gems/capistrano-2.14.1/lib/capistrano/cli/execute.rb:14:in `execute'",
  [35] "/home/kiela/.rvm/gems/ruby-2.1.5@global/gems/capistrano-2.14.1/bin/cap:4:in `<top (required)>'",
  [36] "/home/kiela/.rvm/gems/ruby-2.1.5@global/bin/cap:23:in `load'",
  [37] "/home/kiela/.rvm/gems/ruby-2.1.5@global/bin/cap:23:in `<main>'",
  [38] "/home/kiela/.rvm/gems/ruby-2.1.5@global/bin/ruby_executable_hooks:15:in `eval'",
  [39] "/home/kiela/.rvm/gems/ruby-2.1.5@global/bin/ruby_executable_hooks:15:in `<main>'"
]
```

I tried to google that but any solution which I found doesn't work for me. I would appreciate any suggestions where to look at to fix this problem.

**Comment by kiela** [comment]
Just for future reference:
This issue occurred to me as I had custom entries in my `~/.ssh/config` file for host which I tried to deploy to. The problem was caused because `Net::SSH` lib wasn't able to locate and use correct id_rsa file. This issue was fixed in https://github.com/net-ssh/net-ssh/pull/217

**Comment by leehambley** [comment]
Thanks for the update :)
