### ISSUE TITLE
Don't know how to build task 'production'

### ISSUE THREAD

**Issue by stevenspiel** [capistrano/capistrano#1453]
I have a pretty standard capistrano file (Rails 4.2, Ruby 2.2.2), with required gems in my bundler.

```rb
group :development do
  gem 'capistrano', '~> 3.0', require: false
  gem 'capistrano-rails', '~> 1.1', require: false
  gem 'capistrano-bundler', '~> 1.1', require: false
  gem 'capistrano-passenger', require: false
  gem 'rvm1-capistrano3', require: false
  gem 'capistrano-maintenance', github: 'capistrano/maintenance', require: false
end
```

And my `config/deploy.rb` file looks like this:

```rb
lock '3.3.5'

require 'capistrano'
require 'capistrano/deploy'

set :user, 'user123'
set :stages, %w(production)
set :default_stage, :production

set :application, 'my_app'
set :repo_url, 'git@github.com:user/my_app'

set :tmp_dir, '/var/www/apps/my_app/shared/tmp'
set :rvm1_auto_script_path, '/var/www/apps/my_app/shared/tmp'

set :shared_path, '/var/www/apps/my_app/shared/yml'
set :current_path, '/var/www/my_app'

ask :branch, proc { `git rev-parse --abbrev-ref HEAD`.chomp }.call
set :deploy_to, '/var/www/my_app'

set :pty, true
set :keep_releases, 2
```

and my config/deploy/production.rb file:

```rb
set :rails_env, :production
set :stage, :production

role :app, 'my_app.com'
role :web, 'my_app.com', :primary => true
role :db, 'my_app.com'
```

But running `cap production deploy` keeps giving me the error:

```
$ cap production deploy
cap aborted!
Don't know how to build task 'production'
/Users/stevenspiel/.rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/task_manager.rb:62:in `[]'
/Users/username/.rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/application.rb:149:in `invoke_task'
/Users/username/.rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/Users/username/.rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `each'
/Users/username/.rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `block in top_level'
/Users/username/.rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/application.rb:115:in `run_with_threads'
/Users/username/.rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/application.rb:100:in `top_level'
/Users/username/.rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/application.rb:78:in `block in run'
/Users/username/.rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
/Users/username/.rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'
/Users/username/.rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/capistrano-3.4.0/lib/capistrano/application.rb:15:in `run'
/Users/username/.rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/capistrano-3.4.0/bin/cap:3:in `<top (required)>'
/Users/username/.rbenv/versions/2.0.0-p451/bin/cap:23:in `load'
/Users/username/.rbenv/versions/2.0.0-p451/bin/cap:23:in `<main>'
```

Am I not requiring the correct files?

**Comment by robd** [comment]
What is in your Capfile? Have you checked the [template](https://github.com/capistrano/capistrano/blob/ad61d9288a2567faa5ae37e7fa74b1c1947e592d/lib/capistrano/templates/Capfile#L2)? Do you need to require `capistrano/setup`:

```ruby 
# Load DSL and set up stages
require 'capistrano/setup'
```

**Comment by stevenspiel** [comment]
Ok, I feel like a moron. I was totally missing a Capfile. Thank you!

**Comment by robd** [comment]
@stevenspiel No probs - glad it was something simple! As I understand it, the `require` statements have to be in the Capfile otherwise things don't work properly - see also #1451
