### ISSUE TITLE
Capistrano 3.4.0 Git config doesn't work

### ISSUE THREAD

**Issue by CyborTronik** [capistrano/capistrano#1455]
SCM configuration: 
```
set :repo_url, 'git_user@server:folderurl'
set :scm_passphrase, "git_user_password"
set :scm_verbose, true
```

When I do manually: git clone :repo_url 
Then provide pass that is shown in :scm_passphrase
Everything works OK.

When I do it via capistrano I'm getting next log:
```
   Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).
DEBUG [0d4b4c34]        fatal: The remote end hung up unexpectedly
cap aborted!
SSHKit::Runner::ExecuteError: Exception while executing as stanislav@treaba.me: git exit status: 128
git stdout: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).
fatal: The remote end hung up unexpectedly
git stderr: Nothing written
/home/strifan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sshkit-1.7.1/lib/sshkit/runners/parallel.rb:16:in `rescue in block (2 levels) in execute'
/home/strifan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sshkit-1.7.1/lib/sshkit/runners/parallel.rb:12:in `block (2 levels) in execute'
SSHKit::Command::Failed: git exit status: 128
git stdout: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).
fatal: The remote end hung up unexpectedly
git stderr: Nothing written
```

**Comment by leehambley** [comment]
This isn't an issue with Capistrano rather with your configuration settings. If you had read the CONTRIBUTING file as instructed, you might have posted this, along with some other important information at the Google group where we do support. See you on the other side.
