### ISSUE TITLE
Access denied for user 'engine'@'localhost' (using password: NO)

### ISSUE THREAD

**Issue by ahmed-isam** [capistrano/capistrano#1532]
The project is [here](https://github.com/ahmed-isam/Project-Demeter) working on master, btw, you can figure out how pissed off I am by looking at last night's commits!

I don't know what's going on!!!!!!
```
BUG [d984475f] Command: cd /hgome/deploy/project_demeter/releases/20151201065813 && ( RBENV_ROOT=~/.rbenv RBENV_VERSION=2.2.0 RAILS_ENV=production ~/.rbenv/bin/rbenv exec bundle exec rake db:migrate )
DEBUG [d984475f] 	rake aborted!
DEBUG [d984475f] 	Mysql2::Error: Access denied for user 'engine'@'localhost' (using password: NO)
DEBUG [d984475f] 	/home/deploy/project_demeter/shared/bundle/ruby/2.2.0/gems/mysql2-0.3.18/lib/mysql2/client.rb:70:in `connect'
DEBUG [d984475f] 	/home/deploy/project_demeter/shared/bundle/ruby/2.2.0/gems/mysql2-0.3.18/lib/mysql2/client.rb:70:in `initialize'
DEBUG [d984475f] 	/home/deploy/project_demeter/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/mysql2_adapter.rb:18:in `new'
DEBUG [d984475f] 	/home/deploy/project_demeter/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/mysql2_adapter.rb:18:in `mysql2_connection'
DEBUG [d984475f] 	/home/deploy/project_demeter/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:438:in `new_connection'
DEBUG [d984475f] 	/home/deploy/project_demeter/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:448:in `checkout_new_connection'
DEBUG [d984475f] 	/home/deploy/project_demeter/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:422:in `acquire_connection'
DEBUG [d984475f] 	/home/deploy/project_demeter/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:349:in `block in checkout'
DEBUG [d984475f] 	/home/deploy/project_demeter/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:348:in `checkout'
DEBUG [d984475f] 	/home/deploy/project_demeter/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:263:in `block in connection'
DEBUG [d984475f] 	/home/deploy/project_demeter/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:262:in `connection'
DEBUG [d984475f] 	/home/deploy/project_demeter/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:567:in `retrieve_connection'
DEBUG [d984475f] 	/home/deploy/project_demeter/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/connection_handling.rb:113:in `retrieve_connection'
DEBUG [d984475f] 	/home/deploy/project_demeter/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/connection_handling.rb:87:in `connection'
DEBUG [d984475f] 	/home/deploy/project_demeter/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/migration.rb:913:in `initialize'
DEBUG [d984475f] 	/home/deploy/project_demeter/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/migration.rb:820:in `new'
DEBUG [d984475f] 	/home/deploy/project_demeter/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/migration.rb:820:in `up'
DEBUG [d984475f] 	/home/deploy/project_demeter/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/migration.rb:798:in `migrate'
DEBUG [d984475f] 	/home/deploy/project_demeter/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/tasks/database_tasks.rb:137:in `migrate'
DEBUG [d984475f] 	/home/deploy/project_demeter/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/railties/databases.rake:44:in `block (2 levels) in <top (required)>'
DEBUG [d984475f] 	Tasks: TOP => db:migrate
DEBUG [d984475f] 	(See full trace by running task with --trace)
(Backtrace restricted to imported tasks)
cap aborted!
SSHKit::Runner::ExecuteError: Exception while executing as deploy@104.131.0.195: rake exit status: 1
rake stdout: Nothing written
rake stderr: rake aborted!
Mysql2::Error: Access denied for user 'engine'@'localhost' (using password: NO)
/home/deploy/project_demeter/shared/bundle/ruby/2.2.0/gems/mysql2-0.3.18/lib/mysql2/client.rb:70:in `connect'
/home/deploy/project_demeter/shared/bundle/ruby/2.2.0/gems/mysql2-0.3.18/lib/mysql2/client.rb:70:in `initialize'
/home/deploy/project_demeter/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/mysql2_adapter.rb:18:in `new'
/home/deploy/project_demeter/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/mysql2_adapter.rb:18:in `mysql2_connection'
/home/deploy/project_demeter/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:438:in `new_connection'
/home/deploy/project_demeter/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:448:in `checkout_new_connection'
/home/deploy/project_demeter/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:422:in `acquire_connection'
/home/deploy/project_demeter/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:349:in `block in checkout'
/home/deploy/project_demeter/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:348:in `checkout'
/home/deploy/project_demeter/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:263:in `block in connection'
/home/deploy/project_demeter/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:262:in `connection'
/home/deploy/project_demeter/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:567:in `retrieve_connection'
/home/deploy/project_demeter/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/connection_handling.rb:113:in `retrieve_connection'
/home/deploy/project_demeter/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/connection_handling.rb:87:in `connection'
/home/deploy/project_demeter/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/migration.rb:913:in `initialize'
/home/deploy/project_demeter/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/migration.rb:820:in `new'
/home/deploy/project_demeter/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/migration.rb:820:in `up'
/home/deploy/project_demeter/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/migration.rb:798:in `migrate'
/home/deploy/project_demeter/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/tasks/database_tasks.rb:137:in `migrate'
/home/deploy/project_demeter/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/railties/databases.rake:44:in `block (2 levels) in <top (required)>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)

SSHKit::Command::Failed: rake exit status: 1
rake stdout: Nothing written
rake stderr: rake aborted!
Mysql2::Error: Access denied for user 'engine'@'localhost' (using password: NO)
/home/deploy/project_demeter/shared/bundle/ruby/2.2.0/gems/mysql2-0.3.18/lib/mysql2/client.rb:70:in `connect'
/home/deploy/project_demeter/shared/bundle/ruby/2.2.0/gems/mysql2-0.3.18/lib/mysql2/client.rb:70:in `initialize'
/home/deploy/project_demeter/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/mysql2_adapter.rb:18:in `new'
/home/deploy/project_demeter/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/mysql2_adapter.rb:18:in `mysql2_connection'
/home/deploy/project_demeter/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:438:in `new_connection'
/home/deploy/project_demeter/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:448:in `checkout_new_connection'
/home/deploy/project_demeter/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:422:in `acquire_connection'
/home/deploy/project_demeter/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:349:in `block in checkout'
/home/deploy/project_demeter/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:348:in `checkout'
/home/deploy/project_demeter/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:263:in `block in connection'
/home/deploy/project_demeter/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:262:in `connection'
/home/deploy/project_demeter/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:567:in `retrieve_connection'
/home/deploy/project_demeter/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/connection_handling.rb:113:in `retrieve_connection'
/home/deploy/project_demeter/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/connection_handling.rb:87:in `connection'
/home/deploy/project_demeter/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/migration.rb:913:in `initialize'
/home/deploy/project_demeter/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/migration.rb:820:in `new'
/home/deploy/project_demeter/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/migration.rb:820:in `up'
/home/deploy/project_demeter/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/migration.rb:798:in `migrate'
/home/deploy/project_demeter/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/tasks/database_tasks.rb:137:in `migrate'
/home/deploy/project_demeter/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/railties/databases.rake:44:in `block (2 levels) in <top (required)>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)

Tasks: TOP => deploy:migrate
(See full trace by running task with --trace)
The deploy has failed with an error: Exception while executing as deploy@104.131.0.195: rake exit status: 1
rake stdout: Nothing written
rake stderr: rake aborted!
Mysql2::Error: Access denied for user 'engine'@'localhost' (using password: NO)
/home/deploy/project_demeter/shared/bundle/ruby/2.2.0/gems/mysql2-0.3.18/lib/mysql2/client.rb:70:in `connect'
/home/deploy/project_demeter/shared/bundle/ruby/2.2.0/gems/mysql2-0.3.18/lib/mysql2/client.rb:70:in `initialize'
/home/deploy/project_demeter/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/mysql2_adapter.rb:18:in `new'
/home/deploy/project_demeter/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/mysql2_adapter.rb:18:in `mysql2_connection'
/home/deploy/project_demeter/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:438:in `new_connection'
/home/deploy/project_demeter/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:448:in `checkout_new_connection'
/home/deploy/project_demeter/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:422:in `acquire_connection'
/home/deploy/project_demeter/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:349:in `block in checkout'
/home/deploy/project_demeter/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:348:in `checkout'
/home/deploy/project_demeter/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:263:in `block in connection'
/home/deploy/project_demeter/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:262:in `connection'
/home/deploy/project_demeter/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:567:in `retrieve_connection'
/home/deploy/project_demeter/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/connection_handling.rb:113:in `retrieve_connection'
/home/deploy/project_demeter/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/connection_handling.rb:87:in `connection'
/home/deploy/project_demeter/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/migration.rb:913:in `initialize'
/home/deploy/project_demeter/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/migration.rb:820:in `new'
/home/deploy/project_demeter/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/migration.rb:820:in `up'
/home/deploy/project_demeter/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/migration.rb:798:in `migrate'
/home/deploy/project_demeter/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/tasks/database_tasks.rb:137:in `migrate'
/home/deploy/project_demeter/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/railties/databases.rake:44:in `block (2 levels) in <top (required)>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

**Comment by leehambley** [comment]
Your rails app can't boot because your server doesn't have permission to access the database with the username and password defined in your `database.yml`. You should find a guide on deploying a Rails app `database.yml` or configuring your server correctly for a rails app.

**Comment by ahmed-isam** [comment]
Oh, I see, would you recommend a good guide? Thanks

**Comment by leehambley** [comment]
Google shows me this in the number one position, http://robmclarty.com/blog/how-to-deploy-a-rails-4-app-with-git-and-capistrano if you don't have someone to help you with the server stuff though, beware it can be tricky.
