### ISSUE TITLE
Capistrano DSL breaking 3rd party library

### ISSUE THREAD

**Issue by adamquaile** [capistrano/capistrano#1568]
I've written a simple function to lookup the ip of a digitalocean server using its name using their official gem. This works in isolation, but not in capistrano. 

The snippet looks like this: 
```ruby
require 'droplet_kit'

def digitalocean_ipv4_address_from_server_name(server_name)

    matched = []
    client = DropletKit::Client.new(access_token: 'redacted')
    client.droplets.all().each do |droplet|

        if droplet.name == server_name
            matched.push(droplet)
        end

    end

    if matched.length == 1
        return matched[0].networks.v4[0].ip_address
    end

    raise "Expected 1 server in digital ocean with name #{server_name}, found #{matched.length}."
end

puts digitalocean_ipv4_address_from_server_name('my-do-server-name');

```

And like this in capistrano `staging.rb`
```ruby
require 'droplet_kit'

def digitalocean_ipv4_address_from_server_name(server_name)

    matched = []
    client = DropletKit::Client.new(access_token: 'redacted')
    client.droplets.all().each do |droplet|

        if droplet.name == server_name
            matched.push(droplet)
        end

    end

    if matched.length == 1
        return matched[0].networks.v4[0].ip_address
    end

    raise "Expected 1 server in digital ocean with name #{server_name}, found #{matched.length}."

end

server digitalocean_ipv4_address_from_server_name('my-do-server-name'),
  user: 'deploy',
  roles: %w{app}
```

This results in this error:

```
cap aborted!
ArgumentError: Action 'delete' is already defined on `DropletKit::DropletResource`
/Users/aquaile/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/resource_kit-0.1.4/lib/resource_kit/method_factory.rb:7:in `block in construct'
/Users/aquaile/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/resource_kit-0.1.4/lib/resource_kit/method_factory.rb:4:in `construct'
/Users/aquaile/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/resource_kit-0.1.4/lib/resource_kit/resource.rb:20:in `resources'
/Users/aquaile/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/droplet_kit-1.3.3/lib/droplet_kit/resources/droplet_resource.rb:5:in `<class:DropletResource>'
/Users/aquaile/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/droplet_kit-1.3.3/lib/droplet_kit/resources/droplet_resource.rb:2:in `<module:DropletKit>'
/Users/aquaile/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/droplet_kit-1.3.3/lib/droplet_kit/resources/droplet_resource.rb:1:in `<top (required)>'
/Users/aquaile/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/droplet_kit-1.3.3/lib/droplet_kit/client.rb:22:in `resources'
/Users/aquaile/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/droplet_kit-1.3.3/lib/droplet_kit/client.rb:38:in `method_missing'
config/deploy/staging.rb:8:in `digitalocean_ipv4_address_from_server_name'
config/deploy/staging.rb:24:in `<top (required)>'
/Users/aquaile/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/capistrano-3.4.0/lib/capistrano/setup.rb:15:in `load'
/Users/aquaile/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/capistrano-3.4.0/lib/capistrano/setup.rb:15:in `block (2 levels) in <top (required)>'
/Users/aquaile/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rake/task.rb:240:in `call'
/Users/aquaile/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rake/task.rb:240:in `block in execute'
/Users/aquaile/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rake/task.rb:235:in `each'
/Users/aquaile/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rake/task.rb:235:in `execute'
/Users/aquaile/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rake/task.rb:179:in `block in invoke_with_call_chain'
/Users/aquaile/.rbenv/versions/2.2.3/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/Users/aquaile/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rake/task.rb:172:in `invoke_with_call_chain'
/Users/aquaile/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rake/task.rb:165:in `invoke'
/Users/aquaile/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rake/application.rb:150:in `invoke_task'
/Users/aquaile/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rake/application.rb:106:in `block (2 levels) in top_level'
/Users/aquaile/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rake/application.rb:106:in `each'
/Users/aquaile/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rake/application.rb:106:in `block in top_level'
/Users/aquaile/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rake/application.rb:115:in `run_with_threads'
/Users/aquaile/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rake/application.rb:100:in `top_level'
/Users/aquaile/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rake/application.rb:78:in `block in run'
/Users/aquaile/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rake/application.rb:176:in `standard_exception_handling'
/Users/aquaile/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rake/application.rb:75:in `run'
/Users/aquaile/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/capistrano-3.4.0/lib/capistrano/application.rb:15:in `run'
/Users/aquaile/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/capistrano-3.4.0/bin/cap:3:in `<top (required)>'
/Users/aquaile/.rbenv/versions/2.2.3/bin/cap:23:in `load'
/Users/aquaile/.rbenv/versions/2.2.3/bin/cap:23:in `<main>'
```

After some digging, it looks to me like the capistrano DSL `delete` [^1] method is getting attached to any object. Debugging showed me it was this `#<Method: XYZ(Capistrano::DSL::Env)#delete>` defined here `/Users/aquaile/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/capistrano-3.4.0/lib/capistrano/dsl/env.rb`.

Am I misunderstanding/misusing something, or is this a bug? 

Thanks,
PS. I'm not a ruby developer.. 

[^1]: https://github.com/capistrano/capistrano/commit/7eb7ca01241425225f82594405d020c9c677e615#diff-3059c4778c055b6c4c8ee6eb756f9a02R23

**Comment by mattbrictson** [comment]
I'm not sure this is a bug, but you are right that the way Capistrano and DropletKit are designed are inherently conflicting.

Capistrano does add its DSL to all object. Normally in Capistrano's universe this isn't a problem, since Capistrano is usually used as a standalone tool and not in combination with other libraries or with application code.

I'm not sure we can do much about it, as altering how the Capistrano DSL is defined is probably a big breaking change.

In your case specifically, if you aren't using the DSL `delete` method, you could remove it. Try this before your DropletKit code is executed (e.g. at the bottom of your Capfile):

```ruby
Capistrano::DSL::Env.send(:remove_method, :delete)
```

**Comment by adamquaile** [comment]
@mattbrictson Thanks for the response. I'm not sure that just removing the `delete` method from the DSL would be enough. There are other CRUD sounding methods in that library too, and that sounds like it would just delay trouble until another time I make a change, or get an update. 

Would you also avoid any http abstraction libraries too, and just go for native ruby network requests? It is likely to only be a few calls?

**Comment by mattbrictson** [comment]
To my knowledge, this is the full list of methods that Capistrano mixes in.

```
after
any?
ask
asset_timestamp
before
configure_backend
current_path
default_tasks
define_remote_file_task
delete
deploy_config_path
deploy_path
deploy_to
deploying?
ensure_stage
env
exit_deploy_because_of_exception
fetch
invoke
join_paths
linked_dir_parents
linked_dirs
linked_file_dirs
linked_files
local_user
lock
map_dirnames
now
on
primary
release_path
release_roles
release_timestamp
releases_path
remote_file
repo_path
repo_url
revision_log
revision_log_message
role
role_properties
roles
rollback_log_message
run_locally
scm
server
set
set_if_empty
set_release_path
shared_path
stage_config_path
stage_definitions
stage_set?
stages
sudo
suppress_warnings
t
tasks_without_stage_dependency
```

Personally, I don't think this should be a problem with using HTTP abstraction libraries in general. It is just Digital Ocean's library in particular that seems sensitive to existing method names. Even so, I suspect only `delete` will be a problem, and with the workaround I mentioned, you should be OK.

I'm going to close this because I don't think it is something that Capistrano should fix.

**Comment by mattbrictson** [comment]
I'm reopening this because I think something strange is going on here.

When I load things manually in `irb`, I get no errors:

```ruby
require "capistrano/all"
require "droplet_kit"
client = DropletKit::Client.new(access_token: "redacted")
client.droplets.all().to_a
# => [...]
```

However when I put the same code in `staging.rb`:

```ruby
require "droplet_kit"
client = DropletKit::Client.new(access_token: "redacted")
client.droplets.all().to_a
# => ArgumentError: Action 'delete' is already defined on `DropletKit::DropletResource`
```

This is suspiciously similar to #1528, where the Capistrano DSL is "leaking" into other objects.

**Comment by mattbrictson** [comment]
Ah, never mind. The culprit is `include Capistrano::DSL` in Capistrano's `setup.rb`, which essentially mixes the DSL into all objects, making methods like `delete` defined everywhere. I stand by my [original recommendation](https://github.com/capistrano/capistrano/issues/1568#issuecomment-176939424).
