### ISSUE TITLE
"Deploy failure" cucumber feature is failing

### ISSUE THREAD

**Issue by mattbrictson** [capistrano/capistrano#1636]
This may be due to a recent RuboCop auto-correction gone awry?

```
Feature: Deploy failure

mkdir -p config/deploy
mkdir -p lib/capistrano/tasks
  Background:                                          # features/deploy_failure.feature:3
    Given a test app with the default configuration    # features/step_definitions/setup.rb:1
    And a custom task that will simulate a failure     # features/step_definitions/setup.rb:46
      undefined local variable or method `test_file' for #<Object:0x007f867daf97f8>
      Did you mean?  test_file_exists (NameError)
      ./features/support/remote_command_helpers.rb:19:in `safely_remove_file'
      ./features/step_definitions/setup.rb:47:in `/^a custom task that will simulate a failure$/'
      features/deploy_failure.feature:5:in `And a custom task that will simulate a failure'
    And a custom task to run in the event of a failure # features/step_definitions/setup.rb:51
    And servers with the roles app and web             # features/step_definitions/setup.rb:5
```

**Comment by will-in-wi** [comment]
I'm looking into this. It looks like it might be e7592dbf9dc61702d48913981e1c6dc27019905c.

```diff
diff --git a/features/support/remote_command_helpers.rb b/features/support/remote_command_helpers.rb
index 91420c1..bafdf56 100644
--- a/features/support/remote_command_helpers.rb
+++ b/features/support/remote_command_helpers.rb
@@ -17,8 +17,8 @@ module RemoteCommandHelpers

   def safely_remove_file(_path)
     run_vagrant_command("rm #{test_file}")
-  rescue
-    VagrantHelpers::VagrantSSHCommandError
+  rescue VagrantHelpers::VagrantSSHCommandError
+    nil
   end
 end
```

I'm playing with why this might be an issue.

**Comment by will-in-wi** [comment]
Ah, so I didn't understand how the rescue modifier form worked…

Turns out that the argument to the rescue modifier is actually the return value upon rescue, not the error class being rescued.

To make sure blame is placed where it belongs, Rubocop autocorrect was actually right, and I thought they messed it up and made another manual change to "fix" it. Bah.

Fix in https://github.com/capistrano/capistrano/pull/1637

**Comment by will-in-wi** [comment]
Fix merged. @mattbrictson could you confirm?

Thanks!

**Comment by mattbrictson** [comment]
Confirmed! Tests now pass. :+1:
