### ISSUE TITLE
Rails 5 - Undefined Method 'on' in /capistrano/tasks/rbenv.rake

### ISSUE THREAD

**Issue by kieraneglin** [capistrano/capistrano#1641]
#### Steps to reproduce
1. Setup Rails 5 project as normal
2. Attempt deploy using Capistrano (`bundle exec cap staging deploy --trace`)

#### Expected behaviour
App is deployed to remote server

#### Actual behaviour
NoMethodError is thrown.  Here is the full stack trace:
```
| => bundle exec cap staging deploy --trace
/Users/jeffreyguenther/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/capistrano-3.1.0/lib/capistrano/i18n.rb:4: warning: key :starting is duplicated and overwritten on line 6
** Invoke staging (first_time)
** Execute staging
** Invoke load:defaults (first_time)
** Execute load:defaults
** Invoke bundler:map_bins (first_time)
** Execute bundler:map_bins
** Invoke deploy:set_rails_env (first_time)
** Execute deploy:set_rails_env
** Invoke deploy:set_linked_dirs (first_time)
** Execute deploy:set_linked_dirs
** Invoke deploy:set_rails_env
** Invoke rbenv:validate (first_time)
** Execute rbenv:validate
cap aborted!
NoMethodError: undefined method `on' for main:Object
/Users/jeffreyguenther/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/capistrano-rbenv-2.0.4/lib/capistrano/tasks/rbenv.rake:3:in `block (2 levels) in <top (required)>'
/Users/jeffreyguenther/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-10.5.0/lib/rake/task.rb:240:in `block in execute'
/Users/jeffreyguenther/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-10.5.0/lib/rake/task.rb:235:in `each'
/Users/jeffreyguenther/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-10.5.0/lib/rake/task.rb:235:in `execute'
/Users/jeffreyguenther/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-10.5.0/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/Users/jeffreyguenther/.rbenv/versions/2.3.0/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/Users/jeffreyguenther/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-10.5.0/lib/rake/task.rb:172:in `invoke_with_call_chain'
/Users/jeffreyguenther/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-10.5.0/lib/rake/task.rb:165:in `invoke'
/Users/jeffreyguenther/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/capistrano-3.1.0/lib/capistrano/dsl/task_enhancements.rb:12:in `block in after'
/Users/jeffreyguenther/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-10.5.0/lib/rake/task.rb:240:in `block in execute'
/Users/jeffreyguenther/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-10.5.0/lib/rake/task.rb:235:in `each'
/Users/jeffreyguenther/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-10.5.0/lib/rake/task.rb:235:in `execute'
/Users/jeffreyguenther/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-10.5.0/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/Users/jeffreyguenther/.rbenv/versions/2.3.0/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/Users/jeffreyguenther/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-10.5.0/lib/rake/task.rb:172:in `invoke_with_call_chain'
/Users/jeffreyguenther/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-10.5.0/lib/rake/task.rb:165:in `invoke'
/Users/jeffreyguenther/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-10.5.0/lib/rake/application.rb:150:in `invoke_task'
/Users/jeffreyguenther/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-10.5.0/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/Users/jeffreyguenther/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-10.5.0/lib/rake/application.rb:106:in `each'
/Users/jeffreyguenther/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-10.5.0/lib/rake/application.rb:106:in `block in top_level'
/Users/jeffreyguenther/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-10.5.0/lib/rake/application.rb:115:in `run_with_threads'
/Users/jeffreyguenther/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-10.5.0/lib/rake/application.rb:100:in `top_level'
/Users/jeffreyguenther/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-10.5.0/lib/rake/application.rb:78:in `block in run'
/Users/jeffreyguenther/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-10.5.0/lib/rake/application.rb:176:in `standard_exception_handling'
/Users/jeffreyguenther/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-10.5.0/lib/rake/application.rb:75:in `run'
/Users/jeffreyguenther/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/capistrano-3.1.0/lib/capistrano/application.rb:15:in `run'
/Users/jeffreyguenther/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/capistrano-3.1.0/bin/cap:3:in `<top (required)>'
/Users/jeffreyguenther/.rbenv/versions/2.3.0/bin/cap:23:in `load'
/Users/jeffreyguenther/.rbenv/versions/2.3.0/bin/cap:23:in `<main>'
Tasks: TOP => rbenv:validate
```

#### Configuration

OSX El Capitan

Ruby 2.3.0

Rails 5 Beta 3

Capistrano 3.1

**Comment by kieraneglin** [comment]
### Solved:

Updating Capistrano to 3.4 resolved our error.  Whoops ;)
