### ISSUE TITLE
Better error when nest level is wrong in task block

### ISSUE THREAD

**Issue by kenn** [capistrano/capistrano#1674]
I'm upgrading from v2 and I've hit this error enough times to think that the error could get some love.

What if we define methods on that level to show more user friendly errors? At this point I'm experienced enough to know what it is but don't want to just forget the bitter experience when I started to upgrade.

```ruby
NoMethodError: undefined method `execute' for main:Object
config/deploy.rb:92:in `block (2 levels) in <top (required)>'
.rvm/gems/ruby-2.3.0/gems/rake-11.1.2/lib/rake/task.rb:248:in `block in execute'
.rvm/gems/ruby-2.3.0/gems/rake-11.1.2/lib/rake/task.rb:243:in `each'
.rvm/gems/ruby-2.3.0/gems/rake-11.1.2/lib/rake/task.rb:243:in `execute'
.rvm/gems/ruby-2.3.0/gems/airbrussh-1.0.1/lib/airbrussh/rake/context.rb:55:in `execute'
.rvm/gems/ruby-2.3.0/gems/rake-11.1.2/lib/rake/task.rb:187:in `block in invoke_with_call_chain'
.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
.rvm/gems/ruby-2.3.0/gems/rake-11.1.2/lib/rake/task.rb:180:in `invoke_with_call_chain'
.rvm/gems/ruby-2.3.0/gems/rake-11.1.2/lib/rake/task.rb:173:in `invoke'
.rvm/gems/ruby-2.3.0/gems/rake-11.1.2/lib/rake/application.rb:150:in `invoke_task'
.rvm/gems/ruby-2.3.0/gems/rake-11.1.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
.rvm/gems/ruby-2.3.0/gems/rake-11.1.2/lib/rake/application.rb:106:in `each'
.rvm/gems/ruby-2.3.0/gems/rake-11.1.2/lib/rake/application.rb:106:in `block in top_level'
.rvm/gems/ruby-2.3.0/gems/rake-11.1.2/lib/rake/application.rb:115:in `run_with_threads'
.rvm/gems/ruby-2.3.0/gems/rake-11.1.2/lib/rake/application.rb:100:in `top_level'
.rvm/gems/ruby-2.3.0/gems/rake-11.1.2/lib/rake/application.rb:78:in `block in run'
.rvm/gems/ruby-2.3.0/gems/rake-11.1.2/lib/rake/application.rb:176:in `standard_exception_handling'
.rvm/gems/ruby-2.3.0/gems/rake-11.1.2/lib/rake/application.rb:75:in `run'
.rvm/gems/ruby-2.3.0/gems/capistrano-3.5.0/lib/capistrano/application.rb:14:in `run'
.rvm/gems/ruby-2.3.0/gems/capistrano-3.5.0/bin/cap:3:in `<top (required)>'
.rvm/gems/ruby-2.3.0/bin/cap:23:in `load'
.rvm/gems/ruby-2.3.0/bin/cap:23:in `<main>'
.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by kenn** [comment]
See also http://stackoverflow.com/questions/18838930/how-to-run-shell-commands-on-server-in-capistrano-v3

**Comment by mattbrictson** [comment]
Thanks for the idea! Judging by the number of votes on that SO question, this could definitely help people out.

IMHO better documentation would be the real solution here. But since no one likes writing docs, I would also consider merging a PR along the lines you described to improve the error for a mis-scoped `execute`.

If you (or anyone reading this) wants to help the project, please take a shot at a PR!
