### ISSUE TITLE
cannot find bundler on the instance

### ISSUE THREAD

**Issue by anklos** [capistrano/capistrano#1713]
---

#### Steps to reproduce

1. error: 
  ```
  INFO [a241eba3] Running /usr/bin/env bundle install --path /var/www/vendorable/shared/bundle --without development test --deployment --quiet as ec2-user@54.206.40.113
   DEBUG [a241eba3] Command: cd /var/www/vendorable/releases/20160628045315 && ( export PATH="/home/ec2-user/.rvm/rubies/ruby-2.3.0/bin/:/home/ec2-user/.rvm/gems/ruby-2.3.0/bin/:$PATH" ; /usr/bin/env bundle install --path /var/www/vendorable/shared/bundle --without development test --deployment --quiet )
   DEBUG [a241eba3]       /home/ec2-user/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/dependency.rb:319:in `to_specs'
   DEBUG [a241eba3]       :
   DEBUG [a241eba3]       Could not find 'bundler' (>= 0.a) among 16 total gem(s)
   DEBUG [a241eba3]        (
   DEBUG [a241eba3]       Gem::LoadError
   DEBUG [a241eba3]       )
   DEBUG [a241eba3]       Checked in 'GEM_PATH=/home/ec2-user/.gem/ruby/2.3.0:/home/ec2-user/.rvm/rubies/ruby-2.3.0/lib/ruby/gems/2.3.0', execute `gem env` for more information
   DEBUG [a241eba3]
   DEBUG [a241eba3]               from /home/ec2-user/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/dependency.rb:328:in `to_spec'
   DEBUG [a241eba3]               from /home/ec2-user/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_gem.rb:65:in `gem'
   DEBUG [a241eba3]               from /home/ec2-user/.rvm/gems/ruby-2.3.0/bin//bundle:22:in `<main>'
   DEBUG [a241eba3]               from /home/ec2-user/.rvm/gems/ruby-2.3.0/bin//ruby_executable_hooks:15:in `eval'
   DEBUG [a241eba3]               from /home/ec2-user/.rvm/gems/ruby-2.3.0/bin//ruby_executable_hooks:15:in `<main>'
  ```

2. on instance, `bundle` is included in the `GEM_PATH` as above:

```
$: /home/ec2-user/.rvm/gems/ruby-2.3.0/bin/bundle --version
$: Bundler version 1.12.5
```

#### Expected behaviour

run bundle install

#### Actual behaviour

cannot find bundle bin

#### Paste Capistrano's `doctor` output here (`cap <stage> doctor`):

```
Environment

    Ruby     ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin13]
    Rubygems 2.5.1
    Bundler  1.11.2
    Command  /Users/shaneniu/.rvm/gems/ruby-2.3.0/bin/cap staging doctor

Gems

    capistrano         3.5.0
    airbrussh          1.0.2
    rake               11.2.2
    sshkit             1.11.1
    capistrano-bundler 1.1.4
    capistrano-harrow  0.5.1  (update available)
    capistrano-rails   1.1.7
    capistrano-rvm     0.1.2

Variables

    :application                 "vendorable"
    :assets_prefix               "assets"
    :assets_roles                [:web]
    :branch                      "master"
    :bundle_bins                 ["gem", "rake", "rails"]
    :bundle_flags                "--deployment --quiet"
    :bundle_path                 #<Pathname:/var/www/vendorable/shared/bundle>
    :bundle_roles                :all
    :bundle_servers              [#<Capistrano::Configuration::Server:0x007fb7ae1aa500 @keys=[], @local=false, @user="ec2-user", @hostname="54.206.40.113", @port=nil, @properties=#<Capistrano::Configuration::Server::Properties:0x007fb7ae1a3750 @properties={}, @roles=#<Set: {:web}>>>]
    :bundle_without              "development test"
    :conditionally_migrate       false
    :default_env                 {:path=>"/home/ec2-user/.rvm/rubies/ruby-2.3.0/bin/:/home/ec2-user/.rvm/gems/ruby-2.3.0/bin/:$PATH"}
    :deploy_to                   "/var/www/vendorable"
    :format                      :airbrussh
    :git_environmental_variables {:git_askpass=>"/bin/echo", :git_ssh=>"/tmp/vendorable/git-ssh.sh"}
    :keep_releases               5
    :linked_dirs                 ["public/assets"]
    :linked_files                ["config/database.yml", "tmp/restart.txt"]
    :local_user                  "shaneniu"
    :log_level                   :debug
    :migration_role              "web"
    :migration_servers           #<Capistrano::Configuration::Server:0x007fb7ae1aa500 @keys=[], @local=false, @user="ec2-user", @hostname="54.206.40.113", @port=nil, @properties=#<Capistrano::Configuration::Server::Properties:0x007fb7ae1a3750 @properties={}, @roles=#<Set: {:web}>>>
    :ping_url                    "http://54.206.40.113"
    :pty                         false
    :rails_env                   "staging"
    :repo_url                    "git@github.com:vendorable/vendorable.git"
    :scm                         :git
    :stage                       :staging
    :tmp_dir                     "/tmp"

    :linked_files is not a recognized Capistrano setting (config/deploy.rb:29)
    :ping_url is not a recognized Capistrano setting (config/deploy/staging.rb:23)
```

**Comment by leehambley** [comment]
You might want to reopen this issue on capistrano/bundler

**Comment by anklos** [comment]
find the issue, needs to use bundle binary from wrappers!
