### ISSUE TITLE
Capistrano 3.6.0 breaks when used with Rake < 11.0.0, despite gemspec that allows it

### ISSUE THREAD

**Issue by jesperrojestal** [capistrano/capistrano#1740]
#### Steps to reproduce

1. Have rake version '>= 10.0.0' and '< 11..0.0' installed either via dependencies or specified in Gemfile
2. Install Capistrano
3. bundle exec cap -T --trace

#### Expected behaviour
Should show available capistrano tasks

#### Actual behaviour
```shellsession
cap aborted!
NoMethodError: undefined method `already_invoked' for <Rake::Task load:defaults => []>:Rake::Task
/home/current_user/shared/bundle/ruby/2.2.0/gems/capistrano-3.6.0/lib/capistrano/dsl.rb:16:in `invoke'
/home/current_user/shared/bundle/ruby/2.2.0/gems/capistrano-3.6.0/lib/capistrano/application.rb:91:in `load_imports'
/home/current_user/shared/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:697:in `raw_load_rakefile'
/home/current_user/shared/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:94:in `block in load_rakefile'
/home/current_user/shared/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:176:in `standard_exception_handling'
/home/current_user/shared/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:93:in `load_rakefile'
/home/current_user/shared/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:77:in `block in run'
/home/current_user/shared/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:176:in `standard_exception_handling'
/home/current_user/shared/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:75:in `run'
/home/current_user/shared/bundle/ruby/2.2.0/gems/capistrano-3.6.0/lib/capistrano/application.rb:14:in `run'
/home/current_user/shared/bundle/ruby/2.2.0/gems/capistrano-3.6.0/bin/cap:3:in `<top (required)>'
bin/cap:17:in `load'
bin/cap:17:in `<main>'
```

looking at line 16 of capistrano-3.6.0/lib/capistrano/dsl.rb reveals
```ruby
      if task && task.already_invoked
```
Digging around the rake github repo reveals that Rake::Task#already_invoked is available only in 11.0.0, capistrano.gemspec specifies:
```ruby
  gem.add_dependency "rake", ">= 10.0.0"
```

#### Your configuration
Gemfile contains
```ruby
gem 'rake', '~> 10.5.0'
gem 'capistrano'
```
Paste Capistrano's `doctor` output here (`cap <stage> doctor`):
```shellsession
(Backtrace restricted to imported tasks)
cap aborted!
NoMethodError: undefined method `already_invoked' for <Rake::Task load:defaults => []>:Rake::Task

Tasks: TOP => staging
(See full trace by running task with --trace)
```

#### Workaround
Until gemspec/method is fixed, place rake in Gemfile with version above 11.0.0.
```ruby
gem 'rake',  '~> 11.2.2'
```

**Comment by mattbrictson** [comment]
Thank you very much for the report! Yes, this is a serious bug.

**Comment by mattbrictson** [comment]
@troelskn since this is related to your PR #1730, can you investigate and propose a fix for this? Perhaps we need to monkey patch Rake < 11 to expose `already_invoked`.

**Comment by mattbrictson** [comment]
BTW, this is the Rake PR that exposed `already_invoked`: https://github.com/ruby/rake/pull/93

**Comment by troelskn** [comment]
Yep. I'll take a look at it.
