### ISSUE TITLE
Latest version of mocha breaks Capistrano specs

### ISSUE THREAD

**Issue by mattbrictson** [capistrano/capistrano#1789]
Mocha 1.2.0 was just released. Updating causes Capistrano specs to fail.

### Steps to reproduce

1. In Capistrano master
2. `bundle update`
3. `bundle exec rake`

### Expected behavior

All specs should pass.

### Actual behavior

```
Failures:

  1) Capistrano::Hg::DefaultStrategy#test should call test for repo HEAD
     Failure/Error: context.test(*args)

     NoMethodError:
       private method `test' called for #<#<Class:0x007fb6d241a2b8>:0x007fb6d241a218 @mocha=nil>
     # ./lib/capistrano/scm.rb:27:in `test!'
     # ./lib/capistrano/hg.rb:14:in `test'
     # ./spec/lib/capistrano/hg_spec.rb:27:in `block (3 levels) in <module:Capistrano>'

  2) Capistrano::SCM#initialize should load the provided strategy
     Failure/Error: context.test(*args)

     NoMethodError:
       private method `test' called for #<#<Class:0x007fb6d3051c48>:0x007fb6d3051bf8 @mocha=nil>
     # ./lib/capistrano/scm.rb:27:in `test!'
     # ./spec/lib/capistrano/scm_spec.rb:21:in `test'
     # ./spec/lib/capistrano/scm_spec.rb:36:in `block (3 levels) in <module:Capistrano>'

  3) Capistrano::SCM Convenience methods #test! should return call test on the context
     Failure/Error: context.test(*args)

     NoMethodError:
       private method `test' called for #<#<Class:0x007fb6d2533dc0>:0x007fb6d2533d70 @mocha=nil>
     # ./lib/capistrano/scm.rb:27:in `test!'
     # ./spec/lib/capistrano/scm_spec.rb:46:in `block (4 levels) in <module:Capistrano>'

  4) Capistrano::Svn::DefaultStrategy#test should call test for repo HEAD
     Failure/Error: context.test(*args)

     NoMethodError:
       private method `test' called for #<#<Class:0x007fb6d2613e20>:0x007fb6d2613dd0 @mocha=nil>
     # ./lib/capistrano/scm.rb:27:in `test!'
     # ./lib/capistrano/svn.rb:17:in `test'
     # ./spec/lib/capistrano/svn_spec.rb:30:in `block (3 levels) in <module:Capistrano>'

  5) Capistrano::Svn::DefaultStrategy#check should test the repo url
     Failure/Error: context.test(*args)

     NoMethodError:
       private method `test' called for #<#<Class:0x007fb6d25e3540>:0x007fb6d25e34f0 @mocha=nil>
     # ./lib/capistrano/scm.rb:27:in `test!'
     # ./lib/capistrano/svn.rb:23:in `check'
     # ./spec/lib/capistrano/svn_spec.rb:41:in `block (3 levels) in <module:Capistrano>'

  6) Capistrano::Git::DefaultStrategy#test should call test for repo HEAD
     Failure/Error: context.test(*args)

     NoMethodError:
       private method `test' called for #<#<Class:0x007fb6d25687f0>:0x007fb6d2568750 @mocha=nil>
     # ./lib/capistrano/scm.rb:27:in `test!'
     # ./lib/capistrano/git.rb:16:in `test'
     # ./spec/lib/capistrano/git_spec.rb:27:in `block (3 levels) in <module:Capistrano>'

Finished in 0.84893 seconds (files took 1.04 seconds to load)
361 examples, 6 failures, 2 pending
```

**Comment by caius** [comment]
Figured out a fix for this, it's an interesting one. PR incoming
