### ISSUE TITLE
git plugin causes "fatal: destination path 'xxx' already exists and is not an empty directory" errors when deploying

### ISSUE THREAD

**Issue by paulschreiber** [capistrano/capistrano#1831]
Config:
macOS 10.12.2
ruby 2.4.0 (under rbenv 1.1.0-2-g4f8925a)
Capistrano 3.7.1

After updating to Capistrano 3.7.1, I got this warning:

> [Deprecation Notice] Future versions of Capistrano will not load the Git SCM
> plugin by default. To silence this deprecation warning, add the following to
> your Capfile:
> 
>    require "capistrano/scm/git"
>    install_plugin Capistrano::SCM::Git
> 

I added those lines to my Capfile. It now looks like this:
```
# Load DSL and Setup Up Stages
require 'capistrano/setup'

# Includes default deployment tasks
require 'capistrano/deploy'

require 'capistrano/scm/git'
install_plugin Capistrano::SCM::Git

# Loads custom tasks from `lib/capistrano/tasks' if you have any defined.
Dir.glob('lib/capistrano/tasks/*.rake').each { |r| import r }
```

Running `cap production deploy` fails like so:
```
** Execute git:create_release
00:04 git:create_release
      01 mkdir -p /data/sites/paulschreiber.com/releases/20170118044252
    ✔ 01 paul@shrub.ca 0.110s
      02 git archive master | /usr/bin/env tar -x -f - -C /data/sites/paulschreiber.com/releases/20170118044252
    ✔ 02 paul@shrub.ca 0.581s
      03 git clone -b master --recursive . /data/sites/paulschreiber.com/releases/20170118044252
      03 fatal: destination path '/data/sites/paulschreiber.com/releases/20170118044252' already exists and is not an empty directory.
cap aborted!
SSHKit::Runner::ExecuteError: Exception while executing on host shrub.ca: git exit status: 128
git stdout: Nothing written
git stderr: fatal: destination path '/data/sites/paulschreiber.com/releases/20170118044252' already exists and is not an empty directory.
/Users/paul/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/sshkit-1.11.5/lib/sshkit/runners/parallel.rb:15:in `rescue in block (2 levels) in execute'
/Users/paul/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/sshkit-1.11.5/lib/sshkit/runners/parallel.rb:11:in `block (2 levels) in execute'
SSHKit::Command::Failed: git exit status: 128
git stdout: Nothing written
git stderr: fatal: destination path '/data/sites/paulschreiber.com/releases/20170118044252' already exists and is not an empty directory.
/Users/paul/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/sshkit-1.11.5/lib/sshkit/command.rb:100:in `exit_status='
/Users/paul/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/sshkit-1.11.5/lib/sshkit/backends/netssh.rb:148:in `execute_command'
/Users/paul/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/sshkit-1.11.5/lib/sshkit/backends/abstract.rb:141:in `block in create_command_and_execute'
/Users/paul/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/sshkit-1.11.5/lib/sshkit/backends/abstract.rb:141:in `tap'
/Users/paul/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/sshkit-1.11.5/lib/sshkit/backends/abstract.rb:141:in `create_command_and_execute'
/Users/paul/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/sshkit-1.11.5/lib/sshkit/backends/abstract.rb:74:in `execute'
/Users/paul/.dev/paulschreiber/lib/capistrano/tasks/git.rake:20:in `block (5 levels) in <top (required)>'
/Users/paul/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/sshkit-1.11.5/lib/sshkit/backends/abstract.rb:85:in `within'
/Users/paul/.dev/paulschreiber/lib/capistrano/tasks/git.rake:19:in `block (4 levels) in <top (required)>'
/Users/paul/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/sshkit-1.11.5/lib/sshkit/backends/abstract.rb:93:in `with'
/Users/paul/.dev/paulschreiber/lib/capistrano/tasks/git.rake:18:in `block (3 levels) in <top (required)>'
/Users/paul/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/sshkit-1.11.5/lib/sshkit/backends/abstract.rb:29:in `instance_exec'
/Users/paul/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/sshkit-1.11.5/lib/sshkit/backends/abstract.rb:29:in `run'
/Users/paul/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/sshkit-1.11.5/lib/sshkit/runners/parallel.rb:12:in `block (2 levels) in execute'
Tasks: TOP => git:create_release
The deploy has failed with an error: Exception while executing on host shrub.ca: git exit status: 128
git stdout: Nothing written
git stderr: fatal: destination path '/data/sites/paulschreiber.com/releases/20170118044252' already exists and is not an empty directory.
** Invoke deploy:failed (first_time)
** Execute deploy:failed
```

If I remove those lines, the deploy succeeds.

**Comment by mattbrictson** [comment]
Thanks for the report! It looks like you are customizing Capistrano's behavior. Do you know where this command is coming from?

```
git clone -b master --recursive . /data/sites/paulschreiber.com/releases/20170118044252
```

It may also help to post your `cap production doctor` output so we can look there for clues.

**Comment by paulschreiber** [comment]
I used https://gist.github.com/corny/7459729 to enable submodule support.

In `lib/tasks/git.rake`, I have:
```
namespace :git do
  # from https://gist.github.com/corny/7459729
  # Overrides built-in :create_release method; supports submodules
  task create_release: :'git:update' do
    on roles(:all) do
      with fetch(:git_environmental_variables) do
        within repo_path do
          execute :git, :clone, '-b', fetch(:branch), '--recursive', '.', release_path
        end
      end
    end
  end
end
```

**Comment by mattbrictson** [comment]
Ah, that is the problem.

The reason for the error is that the Gist redefines the `create_release` task. In Capistrano (which is based on Rake), redefining a task *augments* the task instead of replacing it. Thus `create_release` will now execute *both* behaviors: it first does the Capistrano default git behavior (`git archive`) and then does the custom behavior defined by the Gist (`git clone`).

The reason this worked before you upgraded probably has to do with a subtle change in how Capistrano loads the two tasks.

In any case, I would recommend against using that particular Gist. Instead, please check out this plugin, which uses Capistrano's official extension mechanism and is therefore much more reliable:

https://github.com/ekho/capistrano-git-with-submodules
