### ISSUE TITLE
Capistrano Detailed Logs

### ISSUE THREAD

**Issue by serdarsahin** [capistrano/capistrano#1848]
Hi,

As far as I know, there is no log level that can give a problematic server.

We have 150+ servers in one of our `capistrano` deployment scripts, using `cap-ec2` plugin.

Recently, capistrano server couldn't access one of the servers and the deployment was failed. We were getting `ECONNREFUSED` error, and there were no log output that indicates which server was failing.

```
cap aborted!
Errno::ECONNREFUSED: Connection refused - connect(2)
/usr/share/ruby/socket.rb:65:in `connect'
/usr/share/ruby/socket.rb:65:in `connect_internal'
/usr/share/ruby/socket.rb:140:in `connect'
/usr/share/ruby/socket.rb:343:in `block in tcp'
/usr/share/ruby/socket.rb:232:in `each'
/usr/share/ruby/socket.rb:232:in `foreach'
/usr/share/ruby/socket.rb:333:in `tcp'
/usr/local/share/gems/gems/net-ssh-3.1.1/lib/net/ssh/transport/session.rb:70:in `initialize'
/usr/local/share/gems/gems/net-ssh-3.1.1/lib/net/ssh.rb:229:in `new'
/usr/local/share/gems/gems/net-ssh-3.1.1/lib/net/ssh.rb:229:in `start'
/usr/local/share/gems/gems/sshkit-1.9.0/lib/sshkit/backends/connection_pool.rb:59:in `call'
/usr/local/share/gems/gems/sshkit-1.9.0/lib/sshkit/backends/connection_pool.rb:59:in `with'
/usr/local/share/gems/gems/sshkit-1.9.0/lib/sshkit/backends/netssh.rb:134:in `with_ssh'
/usr/local/share/gems/gems/sshkit-1.9.0/lib/sshkit/backends/netssh.rb:87:in `execute_command'
/usr/local/share/gems/gems/sshkit-1.9.0/lib/sshkit/backends/abstract.rb:137:in `block in create_command_and_execute'
/usr/local/share/gems/gems/sshkit-1.9.0/lib/sshkit/backends/abstract.rb:137:in `tap'
/usr/local/share/gems/gems/sshkit-1.9.0/lib/sshkit/backends/abstract.rb:137:in `create_command_and_execute'
/usr/local/share/gems/gems/sshkit-1.9.0/lib/sshkit/backends/abstract.rb:69:in `execute'
/usr/local/share/gems/gems/capistrano-3.5.0/lib/capistrano/tasks/git.rake:16:in `block (3 levels) in <top (required)>'
/usr/local/share/gems/gems/sshkit-1.9.0/lib/sshkit/backends/abstract.rb:29:in `instance_exec'
/usr/local/share/gems/gems/sshkit-1.9.0/lib/sshkit/backends/abstract.rb:29:in `run'
/usr/local/share/gems/gems/sshkit-1.9.0/lib/sshkit/runners/parallel.rb:12:in `block (2 levels) in execute'
Tasks: TOP => git:check => git:wrapper
The deploy has failed with an error: Connection refused - connect(2)
** Invoke deploy:failed (first_time)
** Execute deploy:failed
```

It would be nice to add this to trace output.

**Comment by will-in-wi** [comment]
@serdarsahin, could you upgrade to latest Capistrano and sshkit and post that backtrace? A lot has changed since Capistrano 3.5.0.

Thanks!

**Comment by mattbrictson** [comment]
SSHKit is supposed to add host information to the stack trace but I think this is a legitimate bug, even in the latest version. I'll open an issue. Thanks for the report!

**Comment by mattbrictson** [comment]
Logged here: https://github.com/capistrano/sshkit/issues/389

**Comment by mattbrictson** [comment]
Closing in favor of https://github.com/capistrano/sshkit/issues/389
