### ISSUE TITLE
cap -T is broken when a Capfile is not present in 3.8.0

### ISSUE THREAD

**Issue by seggen-ibuildings** [capistrano/capistrano#1865]
Hi,

I am on OS X (10.12.3, i.e. Sierra). I installed capistrano as described in the docs:

```console
$ gem install capistrano
```

But when I tried to look at the available tasks, I got an error:
```console
$ cap -T --trace
cap aborted!
Don't know how to build task 'load:defaults' (see --tasks)
/Library/Ruby/Gems/2.0.0/gems/rake-12.0.0/lib/rake/task_manager.rb:58:in `[]'
/Library/Ruby/Gems/2.0.0/gems/rake-12.0.0/lib/rake/task.rb:361:in `[]'
/Library/Ruby/Gems/2.0.0/gems/capistrano-3.8.0/lib/capistrano/dsl.rb:15:in `invoke'
/Library/Ruby/Gems/2.0.0/gems/capistrano-3.8.0/lib/capistrano/application.rb:100:in `load_imports'
/Library/Ruby/Gems/2.0.0/gems/rake-12.0.0/lib/rake/application.rb:695:in `raw_load_rakefile'
/Library/Ruby/Gems/2.0.0/gems/rake-12.0.0/lib/rake/application.rb:96:in `block in load_rakefile'
/Library/Ruby/Gems/2.0.0/gems/rake-12.0.0/lib/rake/application.rb:178:in `standard_exception_handling'
/Library/Ruby/Gems/2.0.0/gems/rake-12.0.0/lib/rake/application.rb:95:in `load_rakefile'
/Library/Ruby/Gems/2.0.0/gems/rake-12.0.0/lib/rake/application.rb:79:in `block in run'
/Library/Ruby/Gems/2.0.0/gems/rake-12.0.0/lib/rake/application.rb:178:in `standard_exception_handling'
/Library/Ruby/Gems/2.0.0/gems/rake-12.0.0/lib/rake/application.rb:77:in `run'
/Library/Ruby/Gems/2.0.0/gems/capistrano-3.8.0/lib/capistrano/application.rb:14:in `run'
/Library/Ruby/Gems/2.0.0/gems/capistrano-3.8.0/bin/cap:3:in `<top (required)>'
/usr/local/bin/cap:23:in `load'
/usr/local/bin/cap:23:in `<main>'
```

When I installed Capistrano 3.7.2, I got:

```console
$ cap -T --trace
** Invoke load:defaults (first_time)
** Execute load:defaults
cap install  # Install Capistrano, cap install STAGES=staging,production
```

PS, my Ruby version:

```console
$ ruby --version
ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
```

**Comment by mattbrictson** [comment]
You are right! Not sure how that slipped through. Probably related to #1860.

```
$ cap _3.7.2_ -T
cap install  # Install Capistrano, cap install STAGES=staging,production
$ cap _3.8.0_ -T
(Backtrace restricted to imported tasks)
cap aborted!
Don't know how to build task 'load:defaults' (see --tasks)

(See full trace by running task with --trace)
```

Although to be clear, `cap -T` does work fine if you run it in a project that has a Capfile.

**Comment by mattbrictson** [comment]
Thanks for reporting this! If anyone has an idea for a fix, feel free to open a PR. I may not get to this for a few days.

**Comment by mattbrictson** [comment]
Fun fact: `cap -T` only worked in this scenario due to a happy accident involving the capistrano-harrow gem. Now that capistrano-harrow has been removed, `cap -T` is broken again. 😄 

I should have a fix for this figured out soon.

**Comment by seggen-ibuildings** [comment]
😎
