### ISSUE TITLE
Backtrace of error during deployment shown 4 times

### ISSUE THREAD

**Issue by sriedel** [capistrano/capistrano#1916]
Using capistrano 3.8.2 on MRI ruby 2.4.1 (also happened with 2.3.4 and 2.2.6).

Whenever an error happens during deployment, four backtraces are shown:
- backtrace of the original error
- backtrace of SSHKit::Runner::ExecuteError
- backtrace of rake
- backtrace of capistrano or bundler(?)

Expectation: The backtrace of the upper most error, the other backtraces are not shown since they don't provide any additional information. I.e. if a shell command failed, show the original error backtrace, if sshkit has an issue, display the sshkit backtrace etc.

This is a bit of an annoyance if you want to just quickly see what failed. I'm using a pretty pristine deploy.rb for capistrano 3.8, no log settings were modified from the default.

Example output:
```
00:13 deploy:assets:precompile
      01 /www/project/production/rvm1scripts/rvm-auto.sh . bundle exec rake assets:precompile
      01 rake aborted!
      01 Errno::EACCES: Permission denied @ dir_s_mkdir - /www/project/production/releases/20170829052648/tmp/cache
      01 /www/project/production/shared/bundle/ruby/2.4.0/gems/sprockets-2.11.0/lib/sprockets/cache/file_store.rb:25:…
      01 /www/project/production/shared/bundle/ruby/2.4.0/gems/sprockets-2.11.0/lib/sprockets/caching.rb:34:in `cache…
      01 /www/project/production/shared/bundle/ruby/2.4.0/gems/sprockets-2.11.0/lib/sprockets/caching.rb:92:in `cache…
      01 /www/project/production/shared/bundle/ruby/2.4.0/gems/sprockets-2.11.0/lib/sprockets/caching.rb:63:in `cache…
      01 /www/project/production/shared/bundle/ruby/2.4.0/gems/sprockets-2.11.0/lib/sprockets/index.rb:93:in `build_a…
      01 /www/project/production/shared/bundle/ruby/2.4.0/gems/sprockets-2.11.0/lib/sprockets/base.rb:287:in `find_as…
      01 /www/project/production/shared/bundle/ruby/2.4.0/gems/sprockets-2.11.0/lib/sprockets/index.rb:61:in `find_as…
      01 /www/project/production/shared/bundle/ruby/2.4.0/gems/sprockets-2.11.0/lib/sprockets/manifest.rb:211:in `blo…
      01 /www/project/production/shared/bundle/ruby/2.4.0/gems/sprockets-2.11.0/lib/sprockets/manifest.rb:257:in `ben…
      01 /www/project/production/shared/bundle/ruby/2.4.0/gems/sprockets-2.11.0/lib/sprockets/manifest.rb:210:in `fin…
      01 /www/project/production/shared/bundle/ruby/2.4.0/gems/sprockets-2.11.0/lib/sprockets/manifest.rb:119:in `blo…
      01 /www/project/production/shared/bundle/ruby/2.4.0/gems/sprockets-2.11.0/lib/sprockets/manifest.rb:118:in `eac…
      01 /www/project/production/shared/bundle/ruby/2.4.0/gems/sprockets-2.11.0/lib/sprockets/manifest.rb:118:in `com…
      01 /www/project/production/shared/bundle/ruby/2.4.0/gems/sprockets-rails-2.3.3/lib/sprockets/rails/task.rb:70:i…
      01 /www/project/production/shared/bundle/ruby/2.4.0/gems/sprockets-2.11.0/lib/rake/sprocketstask.rb:146:in `wit…
      01 /www/project/production/shared/bundle/ruby/2.4.0/gems/sprockets-rails-2.3.3/lib/sprockets/rails/task.rb:69:i…
      01 /www/project/production/shared/bundle/ruby/2.4.0/gems/bugsnag-5.3.3/lib/bugsnag/rake.rb:12:in `execute_with_…
      01 /usr/local/rvm/gems/ruby-2.4.1@gemset/gems/bundler-1.15.3/lib/bundler/cli/exec.rb:74:in `load'
      01 /usr/local/rvm/gems/ruby-2.4.1@gemset/gems/bundler-1.15.3/lib/bundler/cli/exec.rb:74:in `kernel_load'
      01 /usr/local/rvm/gems/ruby-2.4.1@gemset/gems/bundler-1.15.3/lib/bundler/cli/exec.rb:27:in `run'
      01 /usr/local/rvm/gems/ruby-2.4.1@gemset/gems/bundler-1.15.3/lib/bundler/cli.rb:365:in `exec'
      01 /usr/local/rvm/gems/ruby-2.4.1@gemset/gems/bundler-1.15.3/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      01 /usr/local/rvm/gems/ruby-2.4.1@gemset/gems/bundler-1.15.3/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `in…
      01 /usr/local/rvm/gems/ruby-2.4.1@gemset/gems/bundler-1.15.3/lib/bundler/vendor/thor/lib/thor.rb:369:in `dispatch'
      01 /usr/local/rvm/gems/ruby-2.4.1@gemset/gems/bundler-1.15.3/lib/bundler/cli.rb:22:in `dispatch'
      01 /usr/local/rvm/gems/ruby-2.4.1@gemset/gems/bundler-1.15.3/lib/bundler/vendor/thor/lib/thor/base.rb:444:in `start'
      01 /usr/local/rvm/gems/ruby-2.4.1@gemset/gems/bundler-1.15.3/lib/bundler/cli.rb:13:in `start'
      01 /usr/local/rvm/gems/ruby-2.4.1@gemset/gems/bundler-1.15.3/exe/bundle:30:in `block in <top (required)>'
      01 /usr/local/rvm/gems/ruby-2.4.1@gemset/gems/bundler-1.15.3/lib/bundler/friendly_errors.rb:121:in `with_friendly_erro…
      01 /usr/local/rvm/gems/ruby-2.4.1@gemset/gems/bundler-1.15.3/exe/bundle:22:in `<top (required)>'
      01 /usr/local/rvm/gems/ruby-2.4.1@gemset/bin/bundle:23:in `load'
      01 /usr/local/rvm/gems/ruby-2.4.1@gemset/bin/bundle:23:in `<main>'
      01 /usr/local/rvm/gems/ruby-2.4.1@gemset/bin/ruby_executable_hooks:15:in `eval'
      01 /usr/local/rvm/gems/ruby-2.4.1@gemset/bin/ruby_executable_hooks:15:in `<main>'
      01 Tasks: TOP => assets:precompile
      01 (See full trace by running task with --trace)
(Backtrace restricted to imported tasks)
cap aborted!
SSHKit::Runner::ExecuteError: Exception while executing on host www1.project.de: rake exit status: 1
rake stdout: rake aborted!
Errno::EACCES: Permission denied @ dir_s_mkdir - /www/project/production/releases/20170829052648/tmp/cache
/www/project/production/shared/bundle/ruby/2.4.0/gems/sprockets-2.11.0/lib/sprockets/cache/file_store.rb:25:in `[]='
/www/project/production/shared/bundle/ruby/2.4.0/gems/sprockets-2.11.0/lib/sprockets/caching.rb:34:in `cache_set'
/www/project/production/shared/bundle/ruby/2.4.0/gems/sprockets-2.11.0/lib/sprockets/caching.rb:92:in `cache_set_hash'
/www/project/production/shared/bundle/ruby/2.4.0/gems/sprockets-2.11.0/lib/sprockets/caching.rb:63:in `cache_asset'
/www/project/production/shared/bundle/ruby/2.4.0/gems/sprockets-2.11.0/lib/sprockets/index.rb:93:in `build_asset'
/www/project/production/shared/bundle/ruby/2.4.0/gems/sprockets-2.11.0/lib/sprockets/base.rb:287:in `find_asset'
/www/project/production/shared/bundle/ruby/2.4.0/gems/sprockets-2.11.0/lib/sprockets/index.rb:61:in `find_asset'
/www/project/production/shared/bundle/ruby/2.4.0/gems/sprockets-2.11.0/lib/sprockets/manifest.rb:211:in `block in find_asset'
/www/project/production/shared/bundle/ruby/2.4.0/gems/sprockets-2.11.0/lib/sprockets/manifest.rb:257:in `benchmark'
/www/project/production/shared/bundle/ruby/2.4.0/gems/sprockets-2.11.0/lib/sprockets/manifest.rb:210:in `find_asset'
/www/project/production/shared/bundle/ruby/2.4.0/gems/sprockets-2.11.0/lib/sprockets/manifest.rb:119:in `block in compile'
/www/project/production/shared/bundle/ruby/2.4.0/gems/sprockets-2.11.0/lib/sprockets/manifest.rb:118:in `each'
/www/project/production/shared/bundle/ruby/2.4.0/gems/sprockets-2.11.0/lib/sprockets/manifest.rb:118:in `compile'
/www/project/production/shared/bundle/ruby/2.4.0/gems/sprockets-rails-2.3.3/lib/sprockets/rails/task.rb:70:in `block (3 levels) in define'
/www/project/production/shared/bundle/ruby/2.4.0/gems/sprockets-2.11.0/lib/rake/sprocketstask.rb:146:in `with_logger'
/www/project/production/shared/bundle/ruby/2.4.0/gems/sprockets-rails-2.3.3/lib/sprockets/rails/task.rb:69:in `block (2 levels) in define'
/www/project/production/shared/bundle/ruby/2.4.0/gems/bugsnag-5.3.3/lib/bugsnag/rake.rb:12:in `execute_with_bugsnag'
/usr/local/rvm/gems/ruby-2.4.1@gemset/gems/bundler-1.15.3/lib/bundler/cli/exec.rb:74:in `load'
/usr/local/rvm/gems/ruby-2.4.1@gemset/gems/bundler-1.15.3/lib/bundler/cli/exec.rb:74:in `kernel_load'
/usr/local/rvm/gems/ruby-2.4.1@gemset/gems/bundler-1.15.3/lib/bundler/cli/exec.rb:27:in `run'
/usr/local/rvm/gems/ruby-2.4.1@gemset/gems/bundler-1.15.3/lib/bundler/cli.rb:365:in `exec'
/usr/local/rvm/gems/ruby-2.4.1@gemset/gems/bundler-1.15.3/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/local/rvm/gems/ruby-2.4.1@gemset/gems/bundler-1.15.3/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/usr/local/rvm/gems/ruby-2.4.1@gemset/gems/bundler-1.15.3/lib/bundler/vendor/thor/lib/thor.rb:369:in `dispatch'
/usr/local/rvm/gems/ruby-2.4.1@gemset/gems/bundler-1.15.3/lib/bundler/cli.rb:22:in `dispatch'
/usr/local/rvm/gems/ruby-2.4.1@gemset/gems/bundler-1.15.3/lib/bundler/vendor/thor/lib/thor/base.rb:444:in `start'
/usr/local/rvm/gems/ruby-2.4.1@gemset/gems/bundler-1.15.3/lib/bundler/cli.rb:13:in `start'
/usr/local/rvm/gems/ruby-2.4.1@gemset/gems/bundler-1.15.3/exe/bundle:30:in `block in <top (required)>'
/usr/local/rvm/gems/ruby-2.4.1@gemset/gems/bundler-1.15.3/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
/usr/local/rvm/gems/ruby-2.4.1@gemset/gems/bundler-1.15.3/exe/bundle:22:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.4.1@gemset/bin/bundle:23:in `load'
/usr/local/rvm/gems/ruby-2.4.1@gemset/bin/bundle:23:in `<main>'
/usr/local/rvm/gems/ruby-2.4.1@gemset/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.4.1@gemset/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => assets:precompile
(See full trace by running task with --trace)
rake stderr: Nothing written

SSHKit::Command::Failed: rake exit status: 1
rake stdout: rake aborted!
Errno::EACCES: Permission denied @ dir_s_mkdir - /www/project/production/releases/20170829052648/tmp/cache
/www/project/production/shared/bundle/ruby/2.4.0/gems/sprockets-2.11.0/lib/sprockets/cache/file_store.rb:25:in `[]='
/www/project/production/shared/bundle/ruby/2.4.0/gems/sprockets-2.11.0/lib/sprockets/caching.rb:34:in `cache_set'
/www/project/production/shared/bundle/ruby/2.4.0/gems/sprockets-2.11.0/lib/sprockets/caching.rb:92:in `cache_set_hash'
/www/project/production/shared/bundle/ruby/2.4.0/gems/sprockets-2.11.0/lib/sprockets/caching.rb:63:in `cache_asset'
/www/project/production/shared/bundle/ruby/2.4.0/gems/sprockets-2.11.0/lib/sprockets/index.rb:93:in `build_asset'
/www/project/production/shared/bundle/ruby/2.4.0/gems/sprockets-2.11.0/lib/sprockets/base.rb:287:in `find_asset'
/www/project/production/shared/bundle/ruby/2.4.0/gems/sprockets-2.11.0/lib/sprockets/index.rb:61:in `find_asset'
/www/project/production/shared/bundle/ruby/2.4.0/gems/sprockets-2.11.0/lib/sprockets/manifest.rb:211:in `block in find_asset'
/www/project/production/shared/bundle/ruby/2.4.0/gems/sprockets-2.11.0/lib/sprockets/manifest.rb:257:in `benchmark'
/www/project/production/shared/bundle/ruby/2.4.0/gems/sprockets-2.11.0/lib/sprockets/manifest.rb:210:in `find_asset'
/www/project/production/shared/bundle/ruby/2.4.0/gems/sprockets-2.11.0/lib/sprockets/manifest.rb:119:in `block in compile'
/www/project/production/shared/bundle/ruby/2.4.0/gems/sprockets-2.11.0/lib/sprockets/manifest.rb:118:in `each'
/www/project/production/shared/bundle/ruby/2.4.0/gems/sprockets-2.11.0/lib/sprockets/manifest.rb:118:in `compile'
/www/project/production/shared/bundle/ruby/2.4.0/gems/sprockets-rails-2.3.3/lib/sprockets/rails/task.rb:70:in `block (3 levels) in define'
/www/project/production/shared/bundle/ruby/2.4.0/gems/sprockets-2.11.0/lib/rake/sprocketstask.rb:146:in `with_logger'
/www/project/production/shared/bundle/ruby/2.4.0/gems/sprockets-rails-2.3.3/lib/sprockets/rails/task.rb:69:in `block (2 levels) in define'
/www/project/production/shared/bundle/ruby/2.4.0/gems/bugsnag-5.3.3/lib/bugsnag/rake.rb:12:in `execute_with_bugsnag'
/usr/local/rvm/gems/ruby-2.4.1@gemset/gems/bundler-1.15.3/lib/bundler/cli/exec.rb:74:in `load'
/usr/local/rvm/gems/ruby-2.4.1@gemset/gems/bundler-1.15.3/lib/bundler/cli/exec.rb:74:in `kernel_load'
/usr/local/rvm/gems/ruby-2.4.1@gemset/gems/bundler-1.15.3/lib/bundler/cli/exec.rb:27:in `run'
/usr/local/rvm/gems/ruby-2.4.1@gemset/gems/bundler-1.15.3/lib/bundler/cli.rb:365:in `exec'
/usr/local/rvm/gems/ruby-2.4.1@gemset/gems/bundler-1.15.3/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/local/rvm/gems/ruby-2.4.1@gemset/gems/bundler-1.15.3/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/usr/local/rvm/gems/ruby-2.4.1@gemset/gems/bundler-1.15.3/lib/bundler/vendor/thor/lib/thor.rb:369:in `dispatch'
/usr/local/rvm/gems/ruby-2.4.1@gemset/gems/bundler-1.15.3/lib/bundler/cli.rb:22:in `dispatch'
/usr/local/rvm/gems/ruby-2.4.1@gemset/gems/bundler-1.15.3/lib/bundler/vendor/thor/lib/thor/base.rb:444:in `start'
/usr/local/rvm/gems/ruby-2.4.1@gemset/gems/bundler-1.15.3/lib/bundler/cli.rb:13:in `start'
/usr/local/rvm/gems/ruby-2.4.1@gemset/gems/bundler-1.15.3/exe/bundle:30:in `block in <top (required)>'
/usr/local/rvm/gems/ruby-2.4.1@gemset/gems/bundler-1.15.3/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
/usr/local/rvm/gems/ruby-2.4.1@gemset/gems/bundler-1.15.3/exe/bundle:22:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.4.1@gemset/bin/bundle:23:in `load'
/usr/local/rvm/gems/ruby-2.4.1@gemset/bin/bundle:23:in `<main>'
/usr/local/rvm/gems/ruby-2.4.1@gemset/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.4.1@gemset/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => assets:precompile
(See full trace by running task with --trace)
rake stderr: Nothing written

Tasks: TOP => deploy:assets:precompile
(See full trace by running task with --trace)
The deploy has failed with an error: Exception while executing on host www1.project.de: rake exit status: 1
rake stdout: rake aborted!
Errno::EACCES: Permission denied @ dir_s_mkdir - /www/project/production/releases/20170829052648/tmp/cache
/www/project/production/shared/bundle/ruby/2.4.0/gems/sprockets-2.11.0/lib/sprockets/cache/file_store.rb:25:in `[]='
/www/project/production/shared/bundle/ruby/2.4.0/gems/sprockets-2.11.0/lib/sprockets/caching.rb:34:in `cache_set'
/www/project/production/shared/bundle/ruby/2.4.0/gems/sprockets-2.11.0/lib/sprockets/caching.rb:92:in `cache_set_hash'
/www/project/production/shared/bundle/ruby/2.4.0/gems/sprockets-2.11.0/lib/sprockets/caching.rb:63:in `cache_asset'
/www/project/production/shared/bundle/ruby/2.4.0/gems/sprockets-2.11.0/lib/sprockets/index.rb:93:in `build_asset'
/www/project/production/shared/bundle/ruby/2.4.0/gems/sprockets-2.11.0/lib/sprockets/base.rb:287:in `find_asset'
/www/project/production/shared/bundle/ruby/2.4.0/gems/sprockets-2.11.0/lib/sprockets/index.rb:61:in `find_asset'
/www/project/production/shared/bundle/ruby/2.4.0/gems/sprockets-2.11.0/lib/sprockets/manifest.rb:211:in `block in find_asset'
/www/project/production/shared/bundle/ruby/2.4.0/gems/sprockets-2.11.0/lib/sprockets/manifest.rb:257:in `benchmark'
/www/project/production/shared/bundle/ruby/2.4.0/gems/sprockets-2.11.0/lib/sprockets/manifest.rb:210:in `find_asset'
/www/project/production/shared/bundle/ruby/2.4.0/gems/sprockets-2.11.0/lib/sprockets/manifest.rb:119:in `block in compile'
/www/project/production/shared/bundle/ruby/2.4.0/gems/sprockets-2.11.0/lib/sprockets/manifest.rb:118:in `each'
/www/project/production/shared/bundle/ruby/2.4.0/gems/sprockets-2.11.0/lib/sprockets/manifest.rb:118:in `compile'
/www/project/production/shared/bundle/ruby/2.4.0/gems/sprockets-rails-2.3.3/lib/sprockets/rails/task.rb:70:in `block (3 levels) in define'
/www/project/production/shared/bundle/ruby/2.4.0/gems/sprockets-2.11.0/lib/rake/sprocketstask.rb:146:in `with_logger'
/www/project/production/shared/bundle/ruby/2.4.0/gems/sprockets-rails-2.3.3/lib/sprockets/rails/task.rb:69:in `block (2 levels) in define'
/www/project/production/shared/bundle/ruby/2.4.0/gems/bugsnag-5.3.3/lib/bugsnag/rake.rb:12:in `execute_with_bugsnag'
/usr/local/rvm/gems/ruby-2.4.1@gemset/gems/bundler-1.15.3/lib/bundler/cli/exec.rb:74:in `load'
/usr/local/rvm/gems/ruby-2.4.1@gemset/gems/bundler-1.15.3/lib/bundler/cli/exec.rb:74:in `kernel_load'
/usr/local/rvm/gems/ruby-2.4.1@gemset/gems/bundler-1.15.3/lib/bundler/cli/exec.rb:27:in `run'
/usr/local/rvm/gems/ruby-2.4.1@gemset/gems/bundler-1.15.3/lib/bundler/cli.rb:365:in `exec'
/usr/local/rvm/gems/ruby-2.4.1@gemset/gems/bundler-1.15.3/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/local/rvm/gems/ruby-2.4.1@gemset/gems/bundler-1.15.3/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/usr/local/rvm/gems/ruby-2.4.1@gemset/gems/bundler-1.15.3/lib/bundler/vendor/thor/lib/thor.rb:369:in `dispatch'
/usr/local/rvm/gems/ruby-2.4.1@gemset/gems/bundler-1.15.3/lib/bundler/cli.rb:22:in `dispatch'
/usr/local/rvm/gems/ruby-2.4.1@gemset/gems/bundler-1.15.3/lib/bundler/vendor/thor/lib/thor/base.rb:444:in `start'
/usr/local/rvm/gems/ruby-2.4.1@gemset/gems/bundler-1.15.3/lib/bundler/cli.rb:13:in `start'
/usr/local/rvm/gems/ruby-2.4.1@gemset/gems/bundler-1.15.3/exe/bundle:30:in `block in <top (required)>'
/usr/local/rvm/gems/ruby-2.4.1@gemset/gems/bundler-1.15.3/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
/usr/local/rvm/gems/ruby-2.4.1@gemset/gems/bundler-1.15.3/exe/bundle:22:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.4.1@gemset/bin/bundle:23:in `load'
/usr/local/rvm/gems/ruby-2.4.1@gemset/bin/bundle:23:in `<main>'
/usr/local/rvm/gems/ruby-2.4.1@gemset/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.4.1@gemset/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => assets:precompile
(See full trace by running task with --trace)
rake stderr: Nothing written

** DEPLOY FAILED
** Refer to log/capistrano.log for details. Here are the last 20 lines:


/www/project/production/shared/bundle/ruby/2.4.0/gems/bugsnag-5.3.3/lib/bugsnag/rake.rb:12:in `execute_with_bugsnag'

/usr/local/rvm/gems/ruby-2.4.1@gemset/gems/bundler-1.15.3/lib/bundler/cli/exec.rb:74:in `load'

/usr/local/rvm/gems/ruby-2.4.1@gemset/gems/bundler-1.15.3/lib/bundler/cli/exec.rb:74:in `kernel_load'

/usr/local/rvm/gems/ruby-2.4.1@gemset/gems/bundler-1.15.3/lib/bundler/cli/exec.rb:27:in `run'

/usr/local/rvm/gems/ruby-2.4.1@gemset/gems/bundler-1.15.3/lib/bundler/cli.rb:365:in `exec'

/usr/local/rvm/gems/ruby-2.4.1@gemset/gems/bundler-1.15.3/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'

/usr/local/rvm/gems/ruby-2.4.1@gemset/gems/bundler-1.15.3/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'

/usr/local/rvm/gems/ruby-2.4.1@gemset/gems/bundler-1.15.3/lib/bundler/vendor/thor/lib/thor.rb:369:in `dispatch'

/usr/local/rvm/gems/ruby-2.4.1@gemset/gems/bundler-1.15.3/lib/bundler/cli.rb:22:in `dispatch'

/usr/local/rvm/gems/ruby-2.4.1@gemset/gems/bundler-1.15.3/lib/bundler/vendor/thor/lib/thor/base.rb:444:in `start'

/usr/local/rvm/gems/ruby-2.4.1@gemset/gems/bundler-1.15.3/lib/bundler/cli.rb:13:in `start'

/usr/local/rvm/gems/ruby-2.4.1@gemset/gems/bundler-1.15.3/exe/bundle:30:in `block in <top (required)>'

/usr/local/rvm/gems/ruby-2.4.1@gemset/gems/bundler-1.15.3/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'

/usr/local/rvm/gems/ruby-2.4.1@gemset/gems/bundler-1.15.3/exe/bundle:22:in `<top (required)>'

/usr/local/rvm/gems/ruby-2.4.1@gemset/bin/bundle:23:in `load'

/usr/local/rvm/gems/ruby-2.4.1@gemset/bin/bundle:23:in `<main>'

/usr/local/rvm/gems/ruby-2.4.1@gemset/bin/ruby_executable_hooks:15:in `eval'

/usr/local/rvm/gems/ruby-2.4.1@gemset/bin/ruby_executable_hooks:15:in `<main>'

 DEBUG [6338b9df]       Tasks: TOP => assets:precompile

(See full trace by running task with --trace)
```

**Comment by leehambley** [comment]
@mattbrictson anything jumping out at you about why this might be the case? I'm not super familiar with AirBruSSH's output, even this looks like the default color printer ` DEBUG [6338b9df]       Tasks: TOP => assets:precompile`

I'd guessed first it was 4x, because 4 servers, but it doesn't look like.

**Comment by sriedel** [comment]
Sorry, you're right, I should have specified: only one server is involved here. If it were four I'd at least understand why things are happening this way.

To fill in a bit more: I'm using SSHKit 1.14.0 and airbrussh 1.3.0.

**Comment by leehambley** [comment]
I'm not sure you are using Airbrussh, the output looks like the default formatter.

Airbrush doesn't include lines like `DEBUG [6338b9df] Tasks `, see the gif on their README https://github.com/mattbrictson/airbrussh

**Comment by sriedel** [comment]
Not sure if you're waiting for a response from me or not.

Anyway, I'm not configuring a logger in any way, neither for capistrano nor for sshkit. What I am seeing is that airbrussh is being required as a dependency by sshkit and from what I'm understanding it's supposed to be the default logger/output handler.

The non-error output during deployments looks just like the gif, strongly implying that it is actually being used.

No idea where the DEBUG output  comes from - as I said regarding output this is a pristine capistrano config.

**Comment by mattbrictson** [comment]
When a deploy fails, Airbrussh dumps the last 20 lines of `log/capistrano.log` to the console for troubleshooting. The log file contains more verbose output, including DEBUG messages. Hence this message:

```
** DEPLOY FAILED
** Refer to log/capistrano.log for details. Here are the last 20 lines:
```

If this feature is providing more harm/confusion than benefit, please open an issue here and we can figure out something better: https://github.com/mattbrictson/airbrussh

That is only a small part of the overall problem, which is that errors are printed multiple times. As far I as I can tell this includes:

1. The output of the failed remote command is printed by Airbrussh (the lines prefixed by `01`).
2. The failed remote command causes an `SSHKit::Command::Failed` exception to be raised.
3. This exception is then wrapped in an `SSHKit::Runner::ExecuteError`.
4. You seem to have the `--trace` flag set, which means the backtraces for these exceptions are also printed.
5. The `SSHKit::Command::Failed` exception contains the stdout and stderr data of the command that failed; this data is printed whenever the exception is printed.

The Capistrano developers have erred on the side of printing all data that we have when an error occurs, to facilitate troubleshooting. But I agree this produces sloppy and redundant output.

I think the first step is to address the double-wrapping of the exception, which is already captured as a feature request here: https://github.com/capistrano/sshkit/issues/348

Once we have a more concise error from SSHkit, we need to make sure Capistrano/Rake/Airbrussh report this better to the user.

**Comment by mattbrictson** [comment]
I will re-word the title of this issue and mark it as a feature request.

**Comment by mattbrictson** [comment]
I mentioned this already in https://github.com/capistrano/sshkit/issues/348#issuecomment-220160838 , but I will reiterate it here:

> the overall error reporting could be much improved from a UX standpoint. If you would like to update this issue with an example of what you think a good error report would look like, we can use that as a spec for building the feature.
