### ISSUE TITLE
deploy:check ArgumentError: Task nil not found

### ISSUE THREAD

**Issue by sergeymishin** [capistrano/capistrano#1940]
Hello,
I just upgraded capistrano from 3.4 to 3.9 (following your upgrade guidelines). And deployment started to fail on `deploy:check` task.

I get `ArgumentError: Task nil not found` after `deploy:check:linked_files` task
`deploy:check:linked_files` seem to execute properly. 

Here's the trace:
```
** Invoke production (first_time)
** Execute production
** Invoke load:defaults (first_time)
** Execute load:defaults
** Invoke rvm:hook (first_time)
** Execute rvm:hook


** Invoke rvm:check (first_time)
** Execute rvm:check
rvm 1.27.0 (latest) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]
rvm 1.26.11 (latest) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]
ruby-2.2.1
ruby-2.2.1
ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-linux]
ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-linux]
** Invoke bundler:map_bins (first_time)
** Execute bundler:map_bins
** Invoke deploy:set_rails_env (first_time)
** Execute deploy:set_rails_env
** Invoke deploy (first_time)
** Execute deploy
** Invoke deploy:starting (first_time)
** Execute deploy:starting
** Invoke deploy:check (first_time)
** Invoke git:check (first_time)
** Invoke git:wrapper (first_time)
** Execute git:wrapper
00:00 git:wrapper
      01 mkdir -p /tmp
    ✔ 01 capdeployer@myappserver1.com 0.283s
    ✔ 01 capdeployer@myappserver2.com 0.361s
      Uploading /tmp/git-ssh-MyApp-production-misher.sh 100.0%
      02 chmod 700 /tmp/git-ssh-MyApp-production-misher.sh
      Uploading /tmp/git-ssh-MyApp-production-misher.sh 100.0%
    ✔ 02 capdeployer@myappserver1.com 0.285s
    ✔ 02 capdeployer@myappserver2.com 0.547s
** Execute git:check
00:02 git:check
      01 git ls-remote git@bitbucket.org:myapp/myapp-api.git HEAD
      01 b86c21782faf19cbd057e5b1750e2e30a232e988
      01
      01 HEAD
      01
    ✔ 01 capdeployer@myappserver2.com 1.158s
      01 b86c21782faf19cbd057e5b1750e2e30a232e988
      01
      01 HEAD
      01
    ✔ 01 capdeployer@myappserver1.com 1.651s
** Execute deploy:check
** Invoke deploy:check:directories (first_time)
** Execute deploy:check:directories
00:03 deploy:check:directories
      01 mkdir -p /home/capdeployer/apps/MyApp/shared /home/capdeployer/apps/MyApp/releases
    ✔ 01 capdeployer@myappserver1.com 0.262s
    ✔ 01 capdeployer@myappserver2.com 0.331s
** Invoke deploy:check:linked_dirs (first_time)
** Execute deploy:check:linked_dirs
00:04 deploy:check:linked_dirs
      01 mkdir -p /home/capdeployer/apps/MyApp/shared/log /home/capdeployer/apps/MyApp/shared/tmp/pids /home/capdeployer/apps/MyApp/shared/tmp/cache /home/capdeployer/apps/MyApp/shared/tmp/sockets /home/capdeployer/ap…
    ✔ 01 capdeployer@myappserver1.com 0.202s
    ✔ 01 capdeployer@myappserver2.com 0.540s
** Invoke deploy:check:make_linked_dirs (first_time)
** Execute deploy:check:make_linked_dirs
00:04 deploy:check:make_linked_dirs
      01 mkdir -p /home/capdeployer/apps/MyApp/shared/config
    ✔ 01 capdeployer@myappserver1.com 0.155s
    ✔ 01 capdeployer@myappserver2.com 0.547s
** Invoke deploy:check:linked_files (first_time)
** Execute deploy:check:linked_files
cap aborted!
ArgumentError: Task nil not found
/Users/misher/.rvm/gems/ruby-2.4.1/gems/capistrano-3.9.1/lib/capistrano/dsl/task_enhancements.rb:15:in `block in after'
/Users/misher/.rvm/gems/ruby-2.4.1/gems/rake-12.1.0/lib/rake/task.rb:251:in `block in execute'
/Users/misher/.rvm/gems/ruby-2.4.1/gems/rake-12.1.0/lib/rake/task.rb:251:in `each'
/Users/misher/.rvm/gems/ruby-2.4.1/gems/rake-12.1.0/lib/rake/task.rb:251:in `execute'
/Users/misher/.rvm/gems/ruby-2.4.1/gems/airbrussh-1.3.0/lib/airbrussh/rake/context.rb:62:in `execute'
/Users/misher/.rvm/gems/ruby-2.4.1/gems/rake-12.1.0/lib/rake/task.rb:195:in `block in invoke_with_call_chain'
/Users/misher/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
/Users/misher/.rvm/gems/ruby-2.4.1/gems/rake-12.1.0/lib/rake/task.rb:188:in `invoke_with_call_chain'
/Users/misher/.rvm/gems/ruby-2.4.1/gems/rake-12.1.0/lib/rake/task.rb:181:in `invoke'
/Users/misher/.rvm/gems/ruby-2.4.1/gems/capistrano-3.9.1/lib/capistrano/dsl.rb:26:in `invoke'
/Users/misher/.rvm/gems/ruby-2.4.1/gems/capistrano-3.9.1/lib/capistrano/tasks/deploy.rake:4:in `block (2 levels) in <top (required)>'
/Users/misher/.rvm/gems/ruby-2.4.1/gems/rake-12.1.0/lib/rake/task.rb:251:in `block in execute'
/Users/misher/.rvm/gems/ruby-2.4.1/gems/rake-12.1.0/lib/rake/task.rb:251:in `each'
/Users/misher/.rvm/gems/ruby-2.4.1/gems/rake-12.1.0/lib/rake/task.rb:251:in `execute'
/Users/misher/.rvm/gems/ruby-2.4.1/gems/airbrussh-1.3.0/lib/airbrussh/rake/context.rb:62:in `execute'
/Users/misher/.rvm/gems/ruby-2.4.1/gems/rake-12.1.0/lib/rake/task.rb:195:in `block in invoke_with_call_chain'
/Users/misher/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
/Users/misher/.rvm/gems/ruby-2.4.1/gems/rake-12.1.0/lib/rake/task.rb:188:in `invoke_with_call_chain'
/Users/misher/.rvm/gems/ruby-2.4.1/gems/rake-12.1.0/lib/rake/task.rb:181:in `invoke'
/Users/misher/.rvm/gems/ruby-2.4.1/gems/capistrano-3.9.1/lib/capistrano/dsl.rb:26:in `invoke'
/Users/misher/.rvm/gems/ruby-2.4.1/gems/capistrano-3.9.1/lib/capistrano/tasks/framework.rake:64:in `block (2 levels) in <top (required)>'
/Users/misher/.rvm/gems/ruby-2.4.1/gems/capistrano-3.9.1/lib/capistrano/tasks/framework.rake:63:in `each'
/Users/misher/.rvm/gems/ruby-2.4.1/gems/capistrano-3.9.1/lib/capistrano/tasks/framework.rake:63:in `block in <top (required)>'
/Users/misher/.rvm/gems/ruby-2.4.1/gems/rake-12.1.0/lib/rake/task.rb:251:in `block in execute'
/Users/misher/.rvm/gems/ruby-2.4.1/gems/rake-12.1.0/lib/rake/task.rb:251:in `each'
/Users/misher/.rvm/gems/ruby-2.4.1/gems/rake-12.1.0/lib/rake/task.rb:251:in `execute'
/Users/misher/.rvm/gems/ruby-2.4.1/gems/airbrussh-1.3.0/lib/airbrussh/rake/context.rb:62:in `execute'
/Users/misher/.rvm/gems/ruby-2.4.1/gems/rake-12.1.0/lib/rake/task.rb:195:in `block in invoke_with_call_chain'
/Users/misher/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
/Users/misher/.rvm/gems/ruby-2.4.1/gems/rake-12.1.0/lib/rake/task.rb:188:in `invoke_with_call_chain'
/Users/misher/.rvm/gems/ruby-2.4.1/gems/rake-12.1.0/lib/rake/task.rb:181:in `invoke'
/Users/misher/.rvm/gems/ruby-2.4.1/gems/rake-12.1.0/lib/rake/application.rb:153:in `invoke_task'
/Users/misher/.rvm/gems/ruby-2.4.1/gems/rake-12.1.0/lib/rake/application.rb:109:in `block (2 levels) in top_level'
/Users/misher/.rvm/gems/ruby-2.4.1/gems/rake-12.1.0/lib/rake/application.rb:109:in `each'
/Users/misher/.rvm/gems/ruby-2.4.1/gems/rake-12.1.0/lib/rake/application.rb:109:in `block in top_level'
/Users/misher/.rvm/gems/ruby-2.4.1/gems/rake-12.1.0/lib/rake/application.rb:118:in `run_with_threads'
/Users/misher/.rvm/gems/ruby-2.4.1/gems/rake-12.1.0/lib/rake/application.rb:103:in `top_level'
/Users/misher/.rvm/gems/ruby-2.4.1/gems/rake-12.1.0/lib/rake/application.rb:81:in `block in run'
/Users/misher/.rvm/gems/ruby-2.4.1/gems/rake-12.1.0/lib/rake/application.rb:179:in `standard_exception_handling'
/Users/misher/.rvm/gems/ruby-2.4.1/gems/rake-12.1.0/lib/rake/application.rb:78:in `run'
/Users/misher/.rvm/gems/ruby-2.4.1/gems/capistrano-3.9.1/lib/capistrano/application.rb:14:in `run'
/Users/misher/.rvm/gems/ruby-2.4.1/gems/capistrano-3.9.1/bin/cap:3:in `<top (required)>'
/Users/misher/.rvm/gems/ruby-2.4.1/bin/cap:23:in `load'
/Users/misher/.rvm/gems/ruby-2.4.1/bin/cap:23:in `<main>'
/Users/misher/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `eval'
/Users/misher/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => deploy:check
The deploy has failed with an error: Task nil not found
** Invoke deploy:failed (first_time)
** Execute deploy:failed
```

### System configuration

```
rvm 1.26.11 (latest) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]
rvm 1.27.0 (latest) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]
ruby-2.2.1
ruby-2.2.1
ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-linux]
ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-linux]

Environment

    Ruby     ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]
    Rubygems 2.6.12
    Bundler  1.15.3
    Command  /Users/misher/.rvm/gems/ruby-2.4.1/bin/cap production doctor

Gems

    capistrano          3.9.1
    airbrussh           1.3.0
    rake                12.1.0
    sshkit              1.14.0
    net-ssh             4.2.0
    capistrano-bundler  1.3.0
    capistrano-rails    1.3.0
    capistrano-rvm      0.1.2
    capistrano3-nginx   2.1.2  (update available)
    capistrano3-unicorn 0.2.1

Variables

    :app_server                     true
    :app_server_socket              "/tmp/unicorn.MyApp_production.sock"
    :application                    "MyApp"
    :branch                         "master"
    :bundle_bins                    ["gem", "rake", "rails"]
    :bundle_binstubs                nil
    :bundle_clean_options           ""
    :bundle_env_variables           {}
    :bundle_flags                   "--deployment --quiet"
    :bundle_gemfile                 nil
    :bundle_jobs                    nil
    :bundle_path                    #<Pathname:/home/capdeployer/apps/MyApp/shared/bundle>
    :bundle_roles                   :all
    :bundle_servers                 [#<Capistrano::Configuration::Server:0x007f7f34a90190 @keys=[], @local=false, @user="capdeployer", @hostname="myappserver1.com", @port=nil, @properties=#<Capistrano::Configuration::Server::Properties:0x007f7f34a91a18 @properties={:primary=>true}, @roles=#<Set: {:web, :app, :db}>>, @ssh_options={:forward_agent=>true}>, #<Capistrano::Configuration::Server:0x007f7f34a8b988 @keys=[], @local=false, @user="capdeployer", @hostname="myappserver2.com", @port=nil, @properties=#<Capistrano::Configuration::Server::Properties:0x007f7f34a8b488 @properties={}, @roles=#<Set: {:web, :app}>>, @ssh_options={:forward_agent=>true}>]
    :bundle_without                 "development test"
    :conditionally_migrate          false
    :default_env                    {}
    :deploy_to                      "/home/capdeployer/apps/MyApp"
    :format                         :airbrussh
    :full_app_name                  "MyApp_production"
    :git_environmental_variables    {:git_askpass=>"/bin/echo", :git_ssh=>"/tmp/git-ssh-MyApp-production-misher.sh"}
    :git_shallow_clone              false
    :git_wrapper_path               "/tmp/git-ssh-MyApp-production-misher.sh"
    :keep_releases                  5
    :linked_dirs                    ["log", "tmp/pids", "tmp/cache", "tmp/sockets", "vendor/bundle", "public/system", "public/uploads", "public/assets", "config/unicorn"]
    :linked_files                   ["config/database.yml", "config/secrets.yml"]
    :local_user                     "misher"
    :log_level                      :debug
    :migration_role                 :db
    :migration_servers              #<Capistrano::Configuration::Server:0x007f7f34a90190 @keys=[], @local=false, @user="capdeployer", @hostname="myappserver1.com", @port=nil, @properties=#<Capistrano::Configuration::Server::Properties:0x007f7f34a91a18 @properties={:primary=>true}, @roles=#<Set: {:web, :app, :db}>>, @ssh_options={:forward_agent=>true}>
    :nginx_domains                  "myappserver1.com"
    :nginx_log_path                 "/home/capdeployer/apps/MyApp/shared/log"
    :nginx_roles                    :web
    :nginx_root_path                "/etc/nginx"
    :nginx_service_path             "service nginx"
    :nginx_sites_available_dir      "sites-available"
    :nginx_sites_enabled_dir        "sites-enabled"
    :nginx_ssl_certificate          "MyApp.crt"
    :nginx_ssl_certificate_key      "MyApp.key"
    :nginx_ssl_certificate_key_path "/etc/ssl/private"
    :nginx_ssl_certificate_path     "/etc/ssl/certs"
    :nginx_static_dir               "public"
    :nginx_sudo_paths               [:nginx_log_path, :nginx_sites_enabled_dir, :nginx_sites_available_dir]
    :nginx_sudo_tasks               ["nginx:start", "nginx:stop", "nginx:restart", "nginx:reload", "nginx:configtest", "nginx:site:add", "nginx:site:disable", "nginx:site:enable", "nginx:site:remove"]
    :nginx_template                 :default
    :nginx_use_ssl                  false
    :private_pub_pid                "/home/capdeployer/apps/MyApp/current/tmp/pids/private_pub.pid"
    :pty                            true
    :rails_env                      :production
    :repo_url                       "git@bitbucket.org:myapp/myapp-api.git"
    :rvm_map_bins                   ["gem", "rake", "ruby", "bundle"]
    :rvm_path                       "~/.rvm"
    :rvm_ruby_version               "2.2.1"
    :rvm_type                       :auto
    :stage                          :production
    :tmp_dir                        "/tmp"
    :unicorn_config_path            "/home/capdeployer/apps/MyApp/shared/config/unicorn/production.rb"
    :unicorn_options                ""
    :unicorn_pid                    "/home/capdeployer/apps/MyApp/current/tmp/pids/unicorn.pid"
    :unicorn_rack_env               "deployment"
    :unicorn_restart_sleep_time     3
    :unicorn_roles                  :app
    :user                           "capdeployer"
    
    :app_server_socket is not a recognized Capistrano setting (/Users/misher/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/delegate.rb:83)
    :nginx_domains is not a recognized Capistrano setting (/Users/misher/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/delegate.rb:83)

Servers (2)

    capdeployer@myappserver1.com     [:web, :app, :db] { :primary => true }
    capdeployer@myappserver2.com [:web, :app]
```

It's the second day I try to solve this problem and find an answer, please help.
Thanks.

**Comment by leehambley** [comment]
Is `capistrano3-nginx 2.1.2 (update available)` a signal that you have an
out of date dependency that is not using the 3.9 API correctly?

Lee Hambley
http://lee.hambley.name/
+49 (0) 170 298 5667

**Comment by sergeymishin** [comment]
Solved. Thank you, Capistrano is awesome!
