### ISSUE TITLE
set :scm, :svn gives wrong deprecation warning advise

### ISSUE THREAD

**Issue by eiked** [capistrano/capistrano#1968]
$ cap -v
Capistrano Version: 3.10.1 (Rake Version: 12.3.0)
---

I had in my Capfile:
`set :scm, :svn`
which resulted in in a deprecation warning (when run with --trace):

From reading the documentation,
I believe that Subversion is now again supported out of the box.
So this should not give warnings.

I actually got different deprecation warnings.

One of them is really wrong (but it must still be there somewhere in the sources)
`    install_plugin Capistrano::SCM::Svnset :branch, `svn info --show-item relative-url`.chomp.sub(/^\^\//, '')
`

```
[Deprecation Notice] `set :scm, :svn` is deprecated.
To ensure your project is compatible with future versions of Capistrano,
remove the :scm setting and instead add these lines to your Capfile after
`require "capistrano/deploy"`:

    require "capistrano/scm/svn"
    install_plugin Capistrano::SCM::Svn
```

However using that advise in my Capfile results in:
```
NoMethodError: undefined method `Svnset' for Capistrano::SCM:Class
config/deploy.rb:9:in `<top (required)>'
/opt/local/lib/ruby2.5/gems/2.5.0/gems/capistrano-3.10.1/lib/capistrano/setup.rb:27:in `load'
```

**Comment by mattbrictson** [comment]
Hi, thanks for the report.

I think the formatting of your issue may have gotten jumbled, because I am having a hard time figuring out exactly what deprecation message you are seeing.

This message is exactly what I would expect you to see, and the instructions it gives are correct:

```
[Deprecation Notice] `set :scm, :svn` is deprecated.
To ensure your project is compatible with future versions of Capistrano,
remove the :scm setting and instead add these lines to your Capfile after
`require "capistrano/deploy"`:

    require "capistrano/scm/svn"
    install_plugin Capistrano::SCM::Svn
```

However you also mention seeing (a different?) message that is "really wrong". Could you elaborate on that, please? Also include your `deploy.rb` if possible, as I suspect that may be part of the problem. Thanks!

Also, to clarify: svn is and has always been supported out of the box. Is there a part of the documentation that suggests otherwise? We can fix it.
