### ISSUE TITLE
FrozenError: can't modify frozen object

### ISSUE THREAD

**Issue by jcoyne** [capistrano/capistrano#2006]
```
bundle exec cap stage prod --trace
** Invoke stage (first_time)
** Execute stage
** Invoke load:defaults (first_time)
** Execute load:defaults
Pseudo-terminal will not be allocated because stdin is not a terminal.
** Invoke bundler:map_bins (first_time)
** Invoke passenger:bundler:hook (first_time)
** Execute passenger:bundler:hook
** Execute bundler:map_bins
** Invoke prod (first_time)
** Execute prod
Skipping task `load:defaults'.
Capistrano tasks may only be invoked once. Since task `load:defaults' was previously invoked, invoke("load:defaults") at /Users/jcoyne/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/capistrano-3.11.0/lib/capistrano/setup.rb:24 will be skipped.
If you really meant to run this task again, use invoke!("load:defaults")
THIS BEHAVIOR MAY CHANGE IN A FUTURE VERSION OF CAPISTRANO. Please join the conversation here if this affects you.
https://github.com/capistrano/capistrano/issues/1686
** Invoke load:defaults
cap aborted!
FrozenError: can't modify frozen object
/Users/jcoyne/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/capistrano-3.11.0/lib/capistrano/setup.rb:25:in `extend_object'
/Users/jcoyne/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/capistrano-3.11.0/lib/capistrano/setup.rb:25:in `extend'
/Users/jcoyne/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/capistrano-3.11.0/lib/capistrano/setup.rb:25:in `block (2 levels) in <top (required)>'
/Users/jcoyne/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rake-12.3.1/lib/rake/task.rb:271:in `block in execute'
/Users/jcoyne/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rake-12.3.1/lib/rake/task.rb:271:in `each'
/Users/jcoyne/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rake-12.3.1/lib/rake/task.rb:271:in `execute'
/Users/jcoyne/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/airbrussh-1.3.0/lib/airbrussh/rake/context.rb:62:in `execute'
/Users/jcoyne/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rake-12.3.1/lib/rake/task.rb:213:in `block in invoke_with_call_chain'
/Users/jcoyne/.rbenv/versions/2.5.3/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
/Users/jcoyne/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rake-12.3.1/lib/rake/task.rb:193:in `invoke_with_call_chain'
/Users/jcoyne/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rake-12.3.1/lib/rake/task.rb:182:in `invoke'
/Users/jcoyne/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rake-12.3.1/lib/rake/application.rb:160:in `invoke_task'
/Users/jcoyne/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rake-12.3.1/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/Users/jcoyne/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rake-12.3.1/lib/rake/application.rb:116:in `each'
/Users/jcoyne/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rake-12.3.1/lib/rake/application.rb:116:in `block in top_level'
/Users/jcoyne/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rake-12.3.1/lib/rake/application.rb:125:in `run_with_threads'
/Users/jcoyne/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rake-12.3.1/lib/rake/application.rb:110:in `top_level'
/Users/jcoyne/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rake-12.3.1/lib/rake/application.rb:83:in `block in run'
/Users/jcoyne/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rake-12.3.1/lib/rake/application.rb:186:in `standard_exception_handling'
/Users/jcoyne/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rake-12.3.1/lib/rake/application.rb:80:in `run'
/Users/jcoyne/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/capistrano-3.11.0/lib/capistrano/application.rb:14:in `run'
/Users/jcoyne/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/capistrano-3.11.0/bin/cap:3:in `<top (required)>'
/Users/jcoyne/.rbenv/versions/2.5.3/bin/cap:23:in `load'
/Users/jcoyne/.rbenv/versions/2.5.3/bin/cap:23:in `<top (required)>'
/Users/jcoyne/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bundler-1.17.1/lib/bundler/cli/exec.rb:74:in `load'
/Users/jcoyne/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bundler-1.17.1/lib/bundler/cli/exec.rb:74:in `kernel_load'
/Users/jcoyne/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bundler-1.17.1/lib/bundler/cli/exec.rb:28:in `run'
/Users/jcoyne/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bundler-1.17.1/lib/bundler/cli.rb:463:in `exec'
/Users/jcoyne/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bundler-1.17.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/Users/jcoyne/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bundler-1.17.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/Users/jcoyne/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bundler-1.17.1/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/Users/jcoyne/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bundler-1.17.1/lib/bundler/cli.rb:27:in `dispatch'
/Users/jcoyne/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bundler-1.17.1/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/Users/jcoyne/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bundler-1.17.1/lib/bundler/cli.rb:18:in `start'
/Users/jcoyne/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bundler-1.17.1/exe/bundle:30:in `block in <top (required)>'
/Users/jcoyne/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bundler-1.17.1/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
/Users/jcoyne/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bundler-1.17.1/exe/bundle:22:in `<top (required)>'
/Users/jcoyne/.rbenv/versions/2.5.3/bin/bundle:23:in `load'
/Users/jcoyne/.rbenv/versions/2.5.3/bin/bundle:23:in `<main>'
Tasks: TOP => prod
Pseudo-terminal will not be allocated because stdin is not a terminal.
```

```
$ cap prod doctor
Pseudo-terminal will not be allocated because stdin is not a terminal.

Environment

    Ruby     ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-darwin18]
    Rubygems 2.7.6
    Bundler  1.17.1
    Command  /Users/jcoyne/.rbenv/versions/2.5.3/bin/cap prod doctor

Gems

    capistrano                3.11.0
    airbrussh                 1.3.0  (update available)
    rake                      12.3.1
    sshkit                    1.18.0
    net-ssh                   5.0.2
    capistrano-bundle_audit   0.2.1
    capistrano-bundler        1.4.0
    capistrano-one_time_key   0.0.1
    capistrano-passenger      0.2.0
    capistrano-shared_configs 0.2.2
    dlss-capistrano           3.4.1

Variables

    :application                     "modsulator-app"
    :branch                          <ask>
    :bundle_audit_ignore             [""]
    :bundle_bins                     ["gem", "rake", "rails", "honeybadger"]
    :bundle_binstubs                 nil
    :bundle_clean_options            ""
    :bundle_env_variables            {}
    :bundle_flags                    "--deployment --quiet"
    :bundle_gemfile                  nil
    :bundle_jobs                     nil
    :bundle_path                     #<Pathname:/opt/app/modsulator/modsulator-app-rails/shared/bundle>
    :bundle_roles                    :all
    :bundle_servers                  [#<Capistrano::Configuration::Server:0x00007fbecf57c048 @keys=[], @local=false, @user="modsulator", @hostname="modsulator-app-rails-prod.stanford.edu", @port=nil, @properties=#<Capistrano::Configuration::Server::Properties:0x00007fbecf3254e8 @properties={}, @roles=#<Set: {:web, :db, :app}>>>]
    :bundle_without                  "test development deploy"
    :chruby_map_bins                 ["honeybadger"]
    :default_env                     {}
    :deploy_to                       "/opt/app/modsulator/modsulator-app-rails"
    :format                          :airbrussh
    :git_environmental_variables     {:git_askpass=>"/bin/echo", :git_ssh=>"/tmp/git-ssh-modsulator-app-prod-jcoyne.sh"}
    :git_shallow_clone               false
    :git_wrapper_path                "/tmp/git-ssh-modsulator-app-prod-jcoyne.sh"
    :honeybadger_env                 :prod
    :keep_releases                   5
    :linked_dirs                     ["log", "tmp"]
    :linked_files                    ["config/secrets.yml", "config/honeybadger.yml"]
    :local_user                      "jcoyne"
    :log_level                       :debug
    :passenger_environment_variables {}
    :passenger_restart_command       "passenger-config restart-app"
    :passenger_restart_limit         2
    :passenger_restart_options       "/opt/app/modsulator/modsulator-app-rails --ignore-app-not-running"
    :passenger_restart_runner        :sequence
    :passenger_restart_wait          5
    :passenger_restart_with_sudo     false
    :passenger_roles                 :app
    :passenger_rvm_ruby_version      nil
    :pty                             false
    :rails_env                       "production"
    :rbenv_map_bins                  ["honeybadger"]
    :repo_url                        "https://github.com/sul-dlss/modsulator-app-rails"
    :rvm_map_bins                    ["honeybadger"]
    :skip_bundle_audit               false
    :ssh_options                     {:keys=>["/var/folders/9t/rygbnddx0b1ckw6tjs3m18qm0000gq/T/d20181106-52308-k2237t/capistrano_key"], :forward_agent=>false, :auth_methods=>["publickey", "password"]}
    :stage                           :prod
    :tmp_dir                         "/tmp"

    :honeybadger_env is not a recognized Capistrano setting (/Users/jcoyne/.rbenv/versions/2.5.3/lib/ruby/2.5.0/delegate.rb:83)
    :linked_dirs is not a recognized Capistrano setting (/Users/jcoyne/.rbenv/versions/2.5.3/lib/ruby/2.5.0/delegate.rb:83)
    :linked_files is not a recognized Capistrano setting (/Users/jcoyne/.rbenv/versions/2.5.3/lib/ruby/2.5.0/delegate.rb:83)
    :rails_env is not a recognized Capistrano setting (/Users/jcoyne/.rbenv/versions/2.5.3/lib/ruby/2.5.0/delegate.rb:83)

Servers (1)

    modsulator@modsulator-app-rails-prod.stanford.edu [:web, :db, :app]

Pseudo-terminal will not be allocated because stdin is not a terminal.
```

**Comment by jcoyne** [comment]
Oops, wrong command was issued.
