### ISSUE TITLE
When I execute cap production deploy ，Show the following error

### ISSUE THREAD

**Issue by AlZero-t** [capistrano/capistrano#2009]
operating system：centos7 3.10.0-693.el7.x86_64
cap：Capistrano Version: 3.11.0 (Rake Version: 11.2.2)
ruby：ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-linux]

```
[root@centos-ops prototype]# cap production deploy --trace
** Invoke production (first_time)
** Execute production
** Invoke load:defaults (first_time)
** Execute load:defaults
cap aborted!
Capfile locked at 3.5.0, but 3.11.0 is loaded
/root/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/capistrano-3.11.0/lib/capistrano/version_validator.rb:9:in `verify'
/root/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/capistrano-3.11.0/lib/capistrano/dsl.rb:65:in `lock'
config/deploy.rb:2:in `<top (required)>'
/root/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/capistrano-3.11.0/lib/capistrano/setup.rb:27:in `load'
/root/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/capistrano-3.11.0/lib/capistrano/setup.rb:27:in `block (3 levels) in <top (required)>'
/root/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/capistrano-3.11.0/lib/capistrano/configuration/variables.rb:32:in `untrusted!'
/root/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/capistrano-3.11.0/lib/capistrano/setup.rb:26:in `block (2 levels) in <top (required)>'
/root/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rake-11.2.2/lib/rake/task.rb:248:in `call'
/root/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rake-11.2.2/lib/rake/task.rb:248:in `block in execute'
/root/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rake-11.2.2/lib/rake/task.rb:243:in `each'
/root/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rake-11.2.2/lib/rake/task.rb:243:in `execute'
/root/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rake-11.2.2/lib/rake/task.rb:187:in `block in invoke_with_call_chain'
/root/.rbenv/versions/2.2.3/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/root/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rake-11.2.2/lib/rake/task.rb:180:in `invoke_with_call_chain'
/root/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rake-11.2.2/lib/rake/task.rb:173:in `invoke'
/root/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rake-11.2.2/lib/rake/application.rb:152:in `invoke_task'
/root/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rake-11.2.2/lib/rake/application.rb:108:in `block (2 levels) in top_level'
/root/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rake-11.2.2/lib/rake/application.rb:108:in `each'
/root/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rake-11.2.2/lib/rake/application.rb:108:in `block in top_level'
/root/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rake-11.2.2/lib/rake/application.rb:117:in `run_with_threads'
/root/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rake-11.2.2/lib/rake/application.rb:102:in `top_level'
/root/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rake-11.2.2/lib/rake/application.rb:80:in `block in run'
/root/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rake-11.2.2/lib/rake/application.rb:178:in `standard_exception_handling'
/root/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rake-11.2.2/lib/rake/application.rb:77:in `run'
/root/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/capistrano-3.11.0/lib/capistrano/application.rb:14:in `run'
/root/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/capistrano-3.11.0/bin/cap:3:in `<top (required)>'
/root/.rbenv/versions/2.2.3/bin/cap:23:in `load'
/root/.rbenv/versions/2.2.3/bin/cap:23:in `<main>'
Tasks: TOP => production
```

**Comment by leehambley** [comment]
```
** Execute load:defaults
cap aborted!
Capfile locked at 3.5.0, but 3.11.0 is loaded
```

This is your problem, please refer to the documentation, and/or the documentation for your shell and dependency manager (likely "Bundler").
