### ISSUE TITLE
1st Deployment fine - ongoing deployments fail - No such file or directory - /usr/bin/env git fetch origin

### ISSUE THREAD

**Issue by bigredkacy** [capistrano/capistrano#2068]
I am able to deploy the first time as expected. When I attempt to redeploy I get the following errors.
The second time I get this error.
Error "Errno::ENOENT: No such file or directory - /usr/bin/env git fetch origin"

**Testing Connection from local to bitbucket**

```
bigre@DESKTOP-30G9FPT MINGW64 /d/WinNMP/WWW/DM-M2/tools/cap (master)
$ ssh -T git@bitbucket.org
logged in as bigredkacy

You can use git or hg to connect to Bitbucket. Shell access is disabled
```

**Testing on the SSH Server to Bitbucket**
`www-dev@917436-staging:03:10 PM:/var/www/dev$ ssh -T git@bitbucket.org
logged in as bigredkacy

You can use git or hg to connect to Bitbucket. Shell access is disabled

Here is the output of the deploy

`
```
bigre@DESKTOP-30G9FPT MINGW64 /d/WinNMP/WWW/DM-M2/tools/cap (master)
$ bundle exec cap dev deploy
00:00 deploy:pending:log
      01 git fetch origin
#<Thread:0x00000000066c0768@C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/sshkit-1.21.0/lib/sshkit/runners/parallel.rb:10 run> terminated with exception (report_on_exception is true):
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/sshkit-1.21.0/lib/sshkit/runners/parallel.rb:15:in `rescue in block (2 levels) in execute': Exception while executing as www-dev@161.47.38.173: No such file or directory - /usr/bin/env git fetch origin (SSHKit::Runner::ExecuteError)
        from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/sshkit-1.21.0/lib/sshkit/runners/parallel.rb:11:in `block (2 levels) in execute'
C:/Ruby26-x64/lib/ruby/2.6.0/open3.rb:213:in `spawn': No such file or directory - /usr/bin/env git fetch origin (Errno::ENOENT)
        from C:/Ruby26-x64/lib/ruby/2.6.0/open3.rb:213:in `popen_run'
        from C:/Ruby26-x64/lib/ruby/2.6.0/open3.rb:101:in `popen3'
        from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/sshkit-1.21.0/lib/sshkit/backends/local.rb:44:in `execute_command'
        from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/sshkit-1.21.0/lib/sshkit/backends/abstract.rb:148:in `block in create_command_and_execute'
        from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/sshkit-1.21.0/lib/sshkit/backends/abstract.rb:148:in `tap'
        from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/sshkit-1.21.0/lib/sshkit/backends/abstract.rb:148:in `create_command_and_execute'
        from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/sshkit-1.21.0/lib/sshkit/backends/abstract.rb:80:in `execute'
        from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/capistrano-magento2-0.9.4/lib/capistrano/tasks/pending.rake:48:in `block (6 levels) in <top (required)>'
        from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/sshkit-1.21.0/lib/sshkit/backends/abstract.rb:31:in `instance_exec'
        from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/sshkit-1.21.0/lib/sshkit/backends/abstract.rb:31:in `run'
        from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/capistrano-3.14.1/lib/capistrano/dsl.rb:76:in `run_locally'
        from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/capistrano-magento2-0.9.4/lib/capistrano/tasks/pending.rake:47:in `block (5 levels) in <top (required)>'
        from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/capistrano-magento2-0.9.4/lib/capistrano/magento2/pending.rb:18:in `ensure_revision'
        from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/capistrano-magento2-0.9.4/lib/capistrano/tasks/pending.rake:45:in `block (4 levels) in <top (required)>'
        from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/sshkit-1.21.0/lib/sshkit/backends/abstract.rb:31:in `instance_exec'
        from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/sshkit-1.21.0/lib/sshkit/backends/abstract.rb:31:in `run'
        from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/sshkit-1.21.0/lib/sshkit/runners/parallel.rb:12:in `block (2 levels) in execute'
(Backtrace restricted to imported tasks)
cap aborted!
SSHKit::Runner::ExecuteError: Exception while executing as www-dev@161.47.38.173: No such file or directory - /usr/bin/env git fetch origin


Caused by:
Errno::ENOENT: No such file or directory - /usr/bin/env git fetch origin

Tasks: TOP => deploy:check => deploy:pending:warn => deploy:pending:log
(See full trace by running task with --trace)
The deploy has failed with an error: Exception while executing as www-dev@161.47.38.173: No such file or directory - /usr/bin/env git fetch origin


** DEPLOY FAILED
** Refer to log/capistrano.log for details. Here are the last 20 lines:


 DEBUG [80b4b91b] Command: [ -f /var/www/delmar-m2/current/REVISION ]

 DEBUG [80b4b91b] Finished in 1.621 seconds with exit status 0 (successful).

  INFO [f4352135] Running /usr/bin/env git fetch origin as bigre@localhost

 DEBUG [f4352135] Command: /usr/bin/env git fetch origin

  INFO ---------------------------------------------------------------------------

  INFO START 2020-10-01 13:03:42 -0700 cap dev deploy

  INFO ---------------------------------------------------------------------------

 DEBUG [0cb253fa] Running [ -f /var/www/delmar-m2/current/REVISION ] as www-dev@161.47.38.173

 DEBUG [0cb253fa] Command: [ -f /var/www/delmar-m2/current/REVISION ]

 DEBUG [0cb253fa] Finished in 1.512 seconds with exit status 0 (successful).

  INFO [2572cef3] Running /usr/bin/env git fetch origin as bigre@localhost

 DEBUG [2572cef3] Command: /usr/bin/env git fetch origin

  INFO ---------------------------------------------------------------------------

  INFO START 2020-10-01 13:04:24 -0700 cap dev deploy

  INFO ---------------------------------------------------------------------------

 DEBUG [b4ef174c] Running [ -f /var/www/delmar-m2/current/REVISION ] as www-dev@161.47.38.173

 DEBUG [b4ef174c] Command: [ -f /var/www/delmar-m2/current/REVISION ]

 DEBUG [b4ef174c] Finished in 1.675 seconds with exit status 0 (successful).

  INFO [3d7e6cc4] Running /usr/bin/env git fetch origin as bigre@localhost

 DEBUG [3d7e6cc4] Command: /usr/bin/env git fetch origin
```
What directory is not found?

Here is the directory of the Remote 
![image](https://user-images.githubusercontent.com/8301644/94858779-6c58ff80-03e8-11eb-8d4e-b72cdbde80c3.png)

SSH the command where it fails in the application/repo/ direction and returns ok
![image](https://user-images.githubusercontent.com/8301644/94859075-d5d90e00-03e8-11eb-8515-2ccf8633cef1.png)

**Comment by mattbrictson** [comment]
Hi @bigredkacy. I'm not sure what is going on but I see in the back trace that SSHKit `local` is being used. That seems very out of place. It looks like you intend to deploy to a remote host. Any idea why `local` is coming into play with your setup? Perhaps you have a capistrano plugin that is changing the standard behavior?

```
from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/sshkit-1.21.0/lib/sshkit/backends/local.rb:44:in `execute_command'
```

If Capistrano tries to run `/usr/bin/env git fetch origin` locally, no surprise that will fail. You want to run that command on the remote host, not locally. `/usr/bin/env` probably doesn't even exist on a Windows PC (it looks like you are running Windows), hence the "No such file or directory" error.

I am not sure if you missed it in our [GitHub issue template](https://github.com/capistrano/capistrano/blob/master/.github/issue_template.md), but it is super helpful if you provide the `cap <stage> doctor` output. Capistrano is a general purpose tool and its behavior is completely different based on settings and plugins, so knowing those things makes it easier to troubleshoot.

**Comment by bigredkacy** [comment]
Thank you for the quick reply and also for the doctor command. I am including that and my deploy.rb and dev.rb if that may help. No where is "local" referenced.

Here is the output. Please note it ends before it is finished @ the variable command, so I added --trace
```
bigre@DESKTOP-30G9FPT MINGW64 /x/var/www/Delmar/tools/cap (master)
$ cap dev doctor --trace
** Invoke dev (first_time)
** Execute dev
** Invoke load:defaults (first_time)
** Execute load:defaults
** Invoke doctor (first_time)
** Invoke doctor:environment (first_time)
** Execute doctor:environment
** Invoke doctor:gems (first_time)
** Execute doctor:gems
** Invoke doctor:variables (first_time)
** Execute doctor:variables
cap aborted!
NameError: uninitialized constant Capistrano::CLI
Did you mean?  CGI
config/deploy/dev.rb:3:in `block in <top (required)>'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/capistrano-3.14.1/lib/capistrano/configuration/variables.rb:54:in `peek'
C:/Ruby26-x64/lib/ruby/2.6.0/delegate.rb:83:in `method_missing'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/capistrano-3.14.1/lib/capistrano/doctor/variables_doctor.rb:57:in `block in inspect_all_values'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/capistrano-3.14.1/lib/capistrano/doctor/variables_doctor.rb:53:in `each'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/capistrano-3.14.1/lib/capistrano/doctor/variables_doctor.rb:53:in `each_with_object'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/capistrano-3.14.1/lib/capistrano/doctor/variables_doctor.rb:53:in `inspect_all_values'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/capistrano-3.14.1/lib/capistrano/doctor/variables_doctor.rb:28:in `call'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/capistrano-3.14.1/lib/capistrano/tasks/doctor.rake:17:in `block (2 levels) in <top (required)>'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rake-13.0.1/lib/rake/task.rb:281:in `block in execute'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rake-13.0.1/lib/rake/task.rb:281:in `each'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rake-13.0.1/lib/rake/task.rb:281:in `execute'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/airbrussh-1.4.0/lib/airbrussh/rake/context.rb:61:in `execute'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rake-13.0.1/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
C:/Ruby26-x64/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rake-13.0.1/lib/rake/task.rb:199:in `invoke_with_call_chain'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rake-13.0.1/lib/rake/task.rb:243:in `block in invoke_prerequisites'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rake-13.0.1/lib/rake/task.rb:241:in `each'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rake-13.0.1/lib/rake/task.rb:241:in `invoke_prerequisites'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rake-13.0.1/lib/rake/task.rb:218:in `block in invoke_with_call_chain'
C:/Ruby26-x64/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rake-13.0.1/lib/rake/task.rb:199:in `invoke_with_call_chain'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rake-13.0.1/lib/rake/task.rb:188:in `invoke'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rake-13.0.1/lib/rake/application.rb:160:in `invoke_task'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rake-13.0.1/lib/rake/application.rb:116:in `block (2 levels) in top_level'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rake-13.0.1/lib/rake/application.rb:116:in `each'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rake-13.0.1/lib/rake/application.rb:116:in `block in top_level'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rake-13.0.1/lib/rake/application.rb:125:in `run_with_threads'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rake-13.0.1/lib/rake/application.rb:110:in `top_level'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rake-13.0.1/lib/rake/application.rb:83:in `block in run'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rake-13.0.1/lib/rake/application.rb:186:in `standard_exception_handling'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rake-13.0.1/lib/rake/application.rb:80:in `run'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/capistrano-3.14.1/lib/capistrano/application.rb:14:in `run'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/capistrano-3.14.1/bin/cap:3:in `<top (required)>'
C:/Ruby26-x64/bin/cap:23:in `load'
C:/Ruby26-x64/bin/cap:23:in `<main>'
Tasks: TOP => doctor => doctor:variables

Environment
    Ruby     ruby 2.6.4p104 (2019-08-28 revision 67798) [x64-mingw32]
    Rubygems 3.0.3
    Bundler  N/A
    Command  C:/Ruby26-x64/bin/cap dev doctor

Gems
    capistrano          3.14.1
    airbrussh           1.4.0
    rake                13.0.1
    sshkit              1.21.0
    net-ssh             6.1.0
    capistrano-magento2 0.9.4

Variables
```
**dev.rb**

```
# Target server connection info
server '161.47.38.173', user: 'www-dev', roles: %w{app web}
set(:user) { Capistrano::CLI.ui.ask "Username=> " }
set :deploy_to, '/var/www/delmar-m2'
set :branch, ENV['BRANCH'] || "master"
set :tmp_dir, '/home/www-dev/tmp2'
```
**deploy.rb**
```
# config valid for current version and patch releases of Capistrano
lock "~> 3.14.1"

set :application, "DMF-M2"
set :repo_url, 'git@bitbucket.org:bigredkacy/delmar.git'
set :user, "www-dev"
```

**Capfile**
```
# Load DSL and set up stages
require 'capistrano/setup'

# Load Magento deployment tasks
require 'capistrano/magento2/deploy'
require 'capistrano/magento2/pending'

# Load Git plugin
require "capistrano/scm/git"
install_plugin Capistrano::SCM::Git

# Load custom tasks from `lib/capistrano/tasks` if you have any defined
Dir.glob('lib/capistrano/tasks/*.rake').each { |r| import r }
```

**Comment by mattbrictson** [comment]
OK it looks like this is a problem with the capistrano-magento2 gem. I took a look at its source code and as you can see it is trying to run the git command locally:

https://github.com/davidalger/capistrano-magento2/blob/3d32c7d654bd9221f67e20c27fc4e62503bdd73d/lib/capistrano/tasks/pending.rake#L47-L49

I suggest that you open an issue in the [capistrano-magento2 repo](https://github.com/davidalger/capistrano-magento2). Hope that helps!

I'll close this issue since it is a third-party bug.
