### ISSUE TITLE
Ruby 3.1: Can't run rubocop on capistrano repo

### ISSUE THREAD

**Issue by mattbrictson** [capistrano/capistrano#2096]
### Steps to reproduce

1. Install Ruby 3.1.
2. In the capistrano repo, run `bundle install`.
3. Run `bundle exec rubocop`

### Expected behavior

Rubocop should run successfully.

### Actual behavior

```
$ ruby -v
ruby 3.1.0p0 (2021-12-25 revision fb4df44d16) [x86_64-darwin20]
$ bundle exec rubocop
wrong number of arguments (given 5, expected 1)
ruby/3.1.0/psych.rb:323:in `safe_load'
ruby/gems/3.1.0/gems/rubocop-0.48.1/lib/rubocop/config_loader.rb:192:in `yaml_safe_load'
ruby/gems/3.1.0/gems/rubocop-0.48.1/lib/rubocop/config_loader.rb:175:in `load_yaml_configuration'
```

**Comment by mattbrictson** [comment]
Seems like the solution is to upgrade to a more recent version of rubocop.
