### ISSUE TITLE
Authentication failed for user

### ISSUE THREAD

**Issue by antoniodisanto92** [capistrano/capistrano#2104]
I have tried everything I could find online like doing ssh-add comments, ssh-agent commands, adding ed25519 and bcrypt_pbkdf but I keep having the same issue.

When I run `cap <environment> deploy`, in different projects, at the first task `deploy:check:directories`, it gets raised an exception and process completely exit saying Authentication failed for the user. If I try do a simple `ssh connection` to the server, everything works fine, same as if I create a custom task using `exec` command. With Capistrano tasks instead I get the error:

```
#<Thread:0x00007fa72c2c45e0@/Users/antoniodisanto/.rvm/gems/ruby-2.5.3@gemset/gems/sshkit-1.18.0/lib/sshkit/runners/parallel.rb:10 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	1: from /Users/antoniodisanto/.rvm/gems/ruby-2.5.3@gemset/gems/sshkit-1.18.0/lib/sshkit/runners/parallel.rb:11:in `block (2 levels) in execute'
/Users/antoniodisanto/.rvm/gems/ruby-2.5.3@gemset/gems/sshkit-1.18.0/lib/sshkit/runners/parallel.rb:15:in `rescue in block (2 levels) in execute': Exception while executing as deploy@********: Authentication failed for user deploy@******** (SSHKit::Runner::ExecuteError)
(Backtrace restricted to imported tasks)
cap aborted!
SSHKit::Runner::ExecuteError: Exception while executing as deploy@*********: Authentication failed for user deploy@*******


Caused by:
Net::SSH::AuthenticationFailed: Authentication failed for user deploy@*********
```

As I've said, if I run a normal `ssh deploy@*******` or even with -vvvv everything works fine with no issues at all. No passphrase is asked either to make it works

Below are the files
Gemfile:
```
source 'https://rubygems.org'

group :development do
  gem 'capistrano', '3.11.0'
  gem 'ed25519', '>= 1.2', '< 2.0'
  gem 'bcrypt_pbkdf', '>= 1.0', '< 2.0'
end

```
Capfile:
```
require "capistrano/setup"
require "capistrano/deploy"
require_relative "config/scm/local_deploy.rb"
install_plugin Capistrano::LocalDeploy

Dir.glob("config/tasks/*.rake").each { |r| import r }

```
deploy.rb:
```
lock '~> 3.11.0'

set :deploy_to, '/home/deploy/directory'
set :user, 'deploy'
set :branch, 'master'
set :tmp_folder, '/tmp/localfolder'
set :repo_url, '**************'

before 'deploy:publishing', 'app:build'
after 'rsync:deploy', 'app:clean'
```
staging.rb:
```
server '**********', roles: %w(app web db staging), user: 'deploy'

set :build_command, 'build-staging'

ask :branch, proc { `git rev-parse --abbrev-ref HEAD`.chomp }
```

I've done a deploy on 2022/01/25 and after, the only thing i've done, is updating MacOSX.

This is the doctor command:
```
cap staging doctor

Environment

    Ruby     ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-darwin21]
    Rubygems 3.0.9
    Bundler  2.1.4
    Command  /Users/antoniodisanto/.rvm/gems/ruby-2.5.3@gemset/bin/cap staging doctor

Gems

    capistrano 3.11.0 (update available)
    airbrussh  1.3.0  (update available)
    rake       12.3.1 (update available)
    sshkit     1.18.0 (update available)
    net-ssh    6.1.0

Variables

    :branch        <ask>
    :build_command "build-staging"
    :default_env   {}
    :deploy_to     "/home/deploy/directory"
    :format        :airbrussh
    :keep_releases 5
    :local_user    "antoniodisanto"
    :log_level     :debug
    :pty           false
    :repo_url      "*************"
    :stage         :staging
    :tmp_dir       "/tmp"
    :tmp_folder    "/tmp/directory"
    :user          "deploy"

    :build_command is not a recognized Capistrano setting (/Users/antoniodisanto/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/delegate.rb:83)
    :tmp_folder is not a recognized Capistrano setting (/Users/antoniodisanto/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/delegate.rb:83)
    :user is not a recognized Capistrano setting (/Users/antoniodisanto/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/delegate.rb:83)

Servers (1)

    deploy@************* [:app, :web, :db, :staging]
```

Thank you!

**Comment by antoniodisanto92** [comment]
Hi, I will close the issue. It wasn't on Capistrano side but was on server side. New openSsh version on server pretend to use a PEM file instead of classical ssh-rsa key.
