### ISSUE TITLE
Deployment fails with Ruby 3.3.0-rc1

### ISSUE THREAD

**Issue by SebastianPoell** [capistrano/capistrano#2146]
Hi guys,

when using capistrano with Ruby 3.3.0-preview3 and 3.3.0-rc1 we discovered some problems during deployment in the "git:check" phase. When using the Ruby version 3.2.2 locally, deployment works perfectly fine every time. But when changing the local Ruby version to the newer ones mentioned above, deployment fails (independent of the installed Ruby version on the server). I'm not sure whether those problems will persist when 3.3.0 is officially released, but I thought it's probably good to report it early. We tested in on two different machines (MacOS and Linux) and got the same error. We also tried to update the relevant gems (capistrano, sshkit, net-ssh, ...) to the latest versions. Any ideas of what's going wrong there? Thx for having a look :)

---

### Steps to reproduce
Install 3.3.0-rc1 and cap deploy

### Actual behavior
Deployment fails within the "git:check"  phase:

```
cap staging deploy
00:00 git:wrapper
...
00:00 git:check
      01 git ls-remote git@github.com:lvOfficial/web.git HEAD
#<Thread:0x00000001030c6b70 ~/.rbenv/versions/3.3.0-rc1/lib/ruby/gems/3.3.0+0/gems/sshkit-1.21.6/lib/sshkit/runners/parallel.rb:10 run> terminated with exception (report_on_exception is true):
~/.rbenv/versions/3.3.0-rc1/lib/ruby/gems/3.3.0+0/gems/sshkit-1.21.6/lib/sshkit/runners/parallel.rb:15:in `rescue in block (2 levels) in execute': Exception while executing as lvdeploy@web99.lv.io: no implicit conversion of nil into String (SSHKit::Runner::ExecuteError)
  from ~/.rbenv/versions/3.3.0-rc1/lib/ruby/gems/3.3.0+0/gems/sshkit-1.21.6/lib/sshkit/runners/parallel.rb:11:in `block (2 levels) in execute'
~/.rbenv/versions/3.3.0-rc1/lib/ruby/gems/3.3.0+0/gems/net-ssh-7.2.0/lib/net/ssh/buffer.rb:146:in `append': no implicit conversion of nil into String (TypeError)

        @content << text
                    ^^^^
  from ~/.rbenv/versions/3.3.0-rc1/lib/ruby/gems/3.3.0+0/gems/net-ssh-7.2.0/lib/net/ssh/buffered_io.rb:66:in `fill'
  from ~/.rbenv/versions/3.3.0-rc1/lib/ruby/gems/3.3.0+0/gems/net-ssh-7.2.0/lib/net/ssh/buffered_io.rb:171:in `fill'
  from ~/.rbenv/versions/3.3.0-rc1/lib/ruby/gems/3.3.0+0/gems/net-ssh-7.2.0/lib/net/ssh/connection/session.rb:275:in `block in ev_do_handle_events'
  from ~/.rbenv/versions/3.3.0-rc1/lib/ruby/gems/3.3.0+0/gems/net-ssh-7.2.0/lib/net/ssh/connection/session.rb:271:in `each'
  from ~/.rbenv/versions/3.3.0-rc1/lib/ruby/gems/3.3.0+0/gems/net-ssh-7.2.0/lib/net/ssh/connection/session.rb:271:in `ev_do_handle_events'
  from ~/.rbenv/versions/3.3.0-rc1/lib/ruby/gems/3.3.0+0/gems/net-ssh-7.2.0/lib/net/ssh/connection/event_loop.rb:117:in `ev_select_and_postprocess'
  from ~/.rbenv/versions/3.3.0-rc1/lib/ruby/gems/3.3.0+0/gems/net-ssh-7.2.0/lib/net/ssh/connection/event_loop.rb:30:in `process'
  from ~/.rbenv/versions/3.3.0-rc1/lib/ruby/gems/3.3.0+0/gems/net-ssh-7.2.0/lib/net/ssh/connection/session.rb:226:in `process'
  from ~/.rbenv/versions/3.3.0-rc1/lib/ruby/gems/3.3.0+0/gems/sshkit-1.21.6/lib/sshkit/backends/connection_pool/cache.rb:76:in `closed?'
  from ~/.rbenv/versions/3.3.0-rc1/lib/ruby/gems/3.3.0+0/gems/sshkit-1.21.6/lib/sshkit/backends/connection_pool/cache.rb:27:in `push'
  from ~/.rbenv/versions/3.3.0-rc1/lib/ruby/gems/3.3.0+0/gems/sshkit-1.21.6/lib/sshkit/backends/connection_pool.rb:67:in `ensure in with'
  from ~/.rbenv/versions/3.3.0-rc1/lib/ruby/gems/3.3.0+0/gems/sshkit-1.21.6/lib/sshkit/backends/connection_pool.rb:70:in `with'
  from ~/.rbenv/versions/3.3.0-rc1/lib/ruby/gems/3.3.0+0/gems/sshkit-1.21.6/lib/sshkit/backends/netssh.rb:177:in `with_ssh'
  from ~/.rbenv/versions/3.3.0-rc1/lib/ruby/gems/3.3.0+0/gems/sshkit-1.21.6/lib/sshkit/backends/netssh.rb:130:in `execute_command'
  from ~/.rbenv/versions/3.3.0-rc1/lib/ruby/gems/3.3.0+0/gems/sshkit-1.21.6/lib/sshkit/backends/abstract.rb:148:in `block in create_command_and_execute'
  from <internal:kernel>:90:in `tap'
  from ~/.rbenv/versions/3.3.0-rc1/lib/ruby/gems/3.3.0+0/gems/sshkit-1.21.6/lib/sshkit/backends/abstract.rb:148:in `create_command_and_execute'
  from ~/.rbenv/versions/3.3.0-rc1/lib/ruby/gems/3.3.0+0/gems/sshkit-1.21.6/lib/sshkit/backends/abstract.rb:80:in `execute'
  from ~/.rbenv/versions/3.3.0-rc1/lib/ruby/gems/3.3.0+0/gems/capistrano-3.18.0/lib/capistrano/scm/git.rb:83:in `git'
  from ~/.rbenv/versions/3.3.0-rc1/lib/ruby/gems/3.3.0+0/gems/capistrano-3.18.0/lib/capistrano/scm/git.rb:40:in `check_repo_is_reachable'
  from ~/.rbenv/versions/3.3.0-rc1/lib/ruby/gems/3.3.0+0/gems/capistrano-3.18.0/lib/capistrano/scm/tasks/git.rake:19:in `block (4 levels) in eval_rakefile'
  from ~/.rbenv/versions/3.3.0-rc1/lib/ruby/gems/3.3.0+0/gems/sshkit-1.21.6/lib/sshkit/backends/abstract.rb:100:in `with'
  from ~/.rbenv/versions/3.3.0-rc1/lib/ruby/gems/3.3.0+0/gems/capistrano-3.18.0/lib/capistrano/scm/tasks/git.rake:18:in `block (3 levels) in eval_rakefile'
  from ~/.rbenv/versions/3.3.0-rc1/lib/ruby/gems/3.3.0+0/gems/sshkit-1.21.6/lib/sshkit/backends/abstract.rb:31:in `instance_exec'
  from ~/.rbenv/versions/3.3.0-rc1/lib/ruby/gems/3.3.0+0/gems/sshkit-1.21.6/lib/sshkit/backends/abstract.rb:31:in `run'
  from ~/.rbenv/versions/3.3.0-rc1/lib/ruby/gems/3.3.0+0/gems/sshkit-1.21.6/lib/sshkit/runners/parallel.rb:12:in `block (2 levels) in execute'
```

### System configuration
```
Environment

    Ruby     ruby 3.3.0rc1 (2023-12-11 master a49643340e) [arm64-darwin23]
    Rubygems 3.5.0.dev
    Bundler  N/A
    Command  ~/.rbenv/versions/3.3.0-rc1/bin/cap staging doctor

Gems

    capistrano         3.18.0
    airbrussh          1.5.0
    rake               13.1.0
    sshkit             1.21.6
    net-ssh            7.2.0
    capistrano-bundler 2.1.0
    capistrano-rails   1.6.3
    capistrano-rbenv   2.2.0

Variables

    :application                            "lv"
    :assets_manifests                       [#<Pathname:/home/lvdeploy/lv/current/public/assets/.sprockets-manifest*>, #<Pathname:/home/lvdeploy/lv/current/public/assets/manifest*.*>]
    :assets_prefix                          "assets"
    :assets_roles                           [:web]
    :branch                                 "switch_to_puma"
    :bundle_bins                            ["gem", "rake", "rails"]
    :bundle_binstubs                        nil
    :bundle_binstubs_command                :install
    :bundle_check_before_install            true
    :bundle_clean_options                   ""
    :bundle_config                          {:deployment=>true}
    :bundle_env_variables                   {}
    :bundle_flags                           "--quiet"
    :bundle_gemfile                         nil
    :bundle_jobs                            4
    :bundle_path                            #<Pathname:/home/lvdeploy/lv/shared/bundle>
    :bundle_roles                           :all
    :bundle_servers                         [#<Capistrano::Configuration::Server:0x000000011ce3f658 @keys=[], @local=false, @user="lvdeploy", @hostname="web99.lv.io", @port=nil, @properties=#<Capistrano::Configuration::Server::Properties:0x000000011cd27ce8 @properties={}, @roles=#<Set: {:app, :web, :db}>>>]
    :bundle_without                         "development:test"
    :conditionally_migrate                  false
    :default_env                            {:rbenv_root=>"$HOME/.rbenv", :rbenv_version=>"3.2.2"}
    :deploy_to                              "/home/lvdeploy/lv"
    :format                                 :airbrussh
    :git_environmental_variables            {:git_askpass=>"/bin/echo", :git_ssh=>"/tmp/git-ssh-ce69bb8d7f7ad89b73ca.sh"}
    :git_max_concurrent_connections         10
    :git_shallow_clone                      false
    :git_wait_interval                      0
    :git_wrapper_path                       "/tmp/git-ssh-ce69bb8d7f7ad89b73ca.sh"
    :keep_assets                            nil
    :keep_releases                          3
    :linked_dirs                            ["log", "tmp/pids", "tmp/cache", "tmp/sockets", "vendor/bundle", "public/assets"]
    :linked_files                           ["config/credentials/staging.key"]
    :local_user                             "sebastianpoll"
    :log_level                              :debug
    :migration_command                      "db:migrate"
    :migration_role                         :db
    :migration_servers                      #<Capistrano::Configuration::Server:0x000000011ce3f658 @keys=[], @local=false, @user="lvdeploy", @hostname="web99.lv.io", @port=nil, @properties=#<Capistrano::Configuration::Server::Properties:0x000000011cd27ce8 @properties={}, @roles=#<Set: {:app, :web, :db}>>>
    :pty                                    false
    :rails_env                              :staging
    :rbenv_map_bins                         ["rake", "gem", "bundle", "ruby", "rails"]
    :rbenv_path                             "$HOME/.rbenv"
    :rbenv_prefix                           "$HOME/.rbenv/bin/rbenv exec"
    :rbenv_roles                            :all
    :rbenv_ruby                             "3.2.2"
    :rbenv_ruby_dir                         "$HOME/.rbenv/versions/3.2.2"
    :repo_url                               "git@github.com:lvOfficial/web.git"
    :ssh_options                            {:keys=>["~/.ssh/id_rsa"], :forward_agent=>true, :auth_methods=>["publickey"]}
    :stage                                  :staging
    :tmp_dir                                "/tmp"
    :whenever_clear_flags                   "--clear-crontab lv"
    :whenever_command                       [:bundle, :exec, :whenever]
    :whenever_command_environment_variables {:rbenv_root=>"$HOME/.rbenv", :rbenv_version=>"3.2.2", :rails_env=>:staging}
    :whenever_environment                   :staging
    :whenever_identifier                    "lv"
    :whenever_load_file                     nil
    :whenever_path                          #<Pathname:/home/lvdeploy/lv/current>
    :whenever_roles                         :db
    :whenever_update_flags                  "--update-crontab lv --set environment=staging"
    :whenever_variables                     "environment=staging"

Servers (1)

    lvdeploy@web99.lv.io [:app, :web, :db]
```

**Comment by mattbrictson** [comment]
This was a bug fixed in net-ssh in https://github.com/net-ssh/net-ssh/pull/928. It looks like the fix has not yet been published to rubygems. Can you try pointing to net-ssh master?

```ruby
gem "net-ssh", github: "net-ssh/net-ssh", branch: "master"
```

**Comment by SebastianPoell** [comment]
Ah, thx for pointing that out! Yes, that fixes it 👍 Side note: If you use that workaround, don't forget to prefix your `cap` commands with `bundle exec`.

**Comment by mattbrictson** [comment]
Closing as fixed upstream in https://github.com/net-ssh/net-ssh/pull/928

**Comment by mattbrictson** [comment]
@SebastianPoell could you test with net-ssh 7.2.1.rc1 that was [just released](https://github.com/net-ssh/net-ssh/pull/928#issuecomment-1858817695)?

**Comment by SebastianPoell** [comment]
@mattbrictson: Jeb, works for me 👍
