### ISSUE TITLE
put action gives `[]=': undefined method `[]=' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by ajjahn** [capistrano/capistrano#548]
When using the `put` action I get the following error:

```
/Users/ajjahn/.rvm/gems/ruby-1.9.3-p392/gems/capistrano-2.15.5/lib/capistrano/transfer.rb:156:in `[]=': undefined method `[]=' for nil:NilClass (NoMethodError)
    from /Users/ajjahn/.rvm/gems/ruby-1.9.3-p392/gems/capistrano-2.15.5/lib/capistrano/transfer.rb:209:in `handle_error'
    from /Users/ajjahn/.rvm/gems/ruby-1.9.3-p392/gems/capistrano-2.15.5/lib/capistrano/transfer.rb:48:in `rescue in block in process!'
    from /Users/ajjahn/.rvm/gems/ruby-1.9.3-p392/gems/capistrano-2.15.5/lib/capistrano/transfer.rb:44:in `block in process!'
    from /Users/ajjahn/.rvm/gems/ruby-1.9.3-p392/gems/capistrano-2.15.5/lib/capistrano/transfer.rb:43:in `loop'
    from /Users/ajjahn/.rvm/gems/ruby-1.9.3-p392/gems/capistrano-2.15.5/lib/capistrano/transfer.rb:43:in `process!'
    from /Users/ajjahn/.rvm/gems/ruby-1.9.3-p392/gems/capistrano-2.15.5/lib/capistrano/transfer.rb:11:in `process'
    from /Users/ajjahn/.rvm/gems/ruby-1.9.3-p392/gems/capistrano-2.15.5/lib/capistrano/configuration/actions/file_transfer.rb:43:in `block in transfer'
    from /Users/ajjahn/.rvm/gems/ruby-1.9.3-p392/gems/capistrano-2.15.5/lib/capistrano/configuration/connections.rb:205:in `block in execute_on_servers'
    from /Users/ajjahn/.rvm/gems/ruby-1.9.3-p392/gems/capistrano-2.15.5/lib/capistrano/configuration/connections.rb:193:in `each'
    from /Users/ajjahn/.rvm/gems/ruby-1.9.3-p392/gems/capistrano-2.15.5/lib/capistrano/configuration/connections.rb:193:in `each_slice'
    from /Users/ajjahn/.rvm/gems/ruby-1.9.3-p392/gems/capistrano-2.15.5/lib/capistrano/configuration/connections.rb:193:in `execute_on_servers'
    from /Users/ajjahn/.rvm/gems/ruby-1.9.3-p392/gems/capistrano-2.15.5/lib/capistrano/configuration/actions/file_transfer.rb:41:in `transfer'
    from /Users/ajjahn/.rvm/gems/ruby-1.9.3-p392/gems/capistrano-2.15.5/lib/capistrano/configuration/actions/file_transfer.rb:26:in `upload'
    from /Users/ajjahn/.rvm/gems/ruby-1.9.3-p392/gems/capistrano-2.15.5/lib/capistrano/configuration/actions/file_transfer.rb:13:in `put'
    from /Users/ajjahn/.rvm/gems/ruby-1.9.3-p392/gems/capistrano-2.15.5/lib/capistrano/configuration/namespaces.rb:191:in `method_missing'
    from ./config/deploy.rb:60:in `block (2 levels) in load'
    from /Users/ajjahn/.rvm/gems/ruby-1.9.3-p392/gems/capistrano-2.15.5/lib/capistrano/configuration/execution.rb:138:in `instance_eval'
    from /Users/ajjahn/.rvm/gems/ruby-1.9.3-p392/gems/capistrano-2.15.5/lib/capistrano/configuration/execution.rb:138:in `invoke_task_directly'
    from /Users/ajjahn/.rvm/gems/ruby-1.9.3-p392/gems/capistrano-2.15.5/lib/capistrano/configuration/callbacks.rb:25:in `invoke_task_directly_with_callbacks'
    from /Users/ajjahn/.rvm/gems/ruby-1.9.3-p392/gems/capistrano-2.15.5/lib/capistrano/configuration/execution.rb:89:in `execute_task'
    from /Users/ajjahn/.rvm/gems/ruby-1.9.3-p392/gems/capistrano-2.15.5/lib/capistrano/configuration/execution.rb:101:in `find_and_execute_task'
    from /Users/ajjahn/.rvm/gems/ruby-1.9.3-p392/gems/capistrano-2.15.5/lib/capistrano/callback.rb:38:in `call'
    from /Users/ajjahn/.rvm/gems/ruby-1.9.3-p392/gems/capistrano-2.15.5/lib/capistrano/configuration/callbacks.rb:141:in `block in trigger'
    from /Users/ajjahn/.rvm/gems/ruby-1.9.3-p392/gems/capistrano-2.15.5/lib/capistrano/configuration/callbacks.rb:141:in `each'
    from /Users/ajjahn/.rvm/gems/ruby-1.9.3-p392/gems/capistrano-2.15.5/lib/capistrano/configuration/callbacks.rb:141:in `trigger'
    from /Users/ajjahn/.rvm/gems/ruby-1.9.3-p392/gems/capistrano-2.15.5/lib/capistrano/configuration/callbacks.rb:27:in `invoke_task_directly_with_callbacks'
    from /Users/ajjahn/.rvm/gems/ruby-1.9.3-p392/gems/capistrano-2.15.5/lib/capistrano/configuration/execution.rb:89:in `execute_task'
    from /Users/ajjahn/.rvm/gems/ruby-1.9.3-p392/gems/capistrano-2.15.5/lib/capistrano/configuration/execution.rb:101:in `find_and_execute_task'
    from /Users/ajjahn/.rvm/gems/ruby-1.9.3-p392/gems/capistrano-2.15.5/lib/capistrano/cli/execute.rb:46:in `block in execute_requested_actions'
    from /Users/ajjahn/.rvm/gems/ruby-1.9.3-p392/gems/capistrano-2.15.5/lib/capistrano/cli/execute.rb:45:in `each'
    from /Users/ajjahn/.rvm/gems/ruby-1.9.3-p392/gems/capistrano-2.15.5/lib/capistrano/cli/execute.rb:45:in `execute_requested_actions'
    from /Users/ajjahn/.rvm/gems/ruby-1.9.3-p392/gems/capistrano-2.15.5/lib/capistrano/cli/help.rb:19:in `execute_requested_actions_with_help'
    from /Users/ajjahn/.rvm/gems/ruby-1.9.3-p392/gems/capistrano-2.15.5/lib/capistrano/cli/execute.rb:34:in `execute!'
    from /Users/ajjahn/.rvm/gems/ruby-1.9.3-p392/gems/capistrano-2.15.5/lib/capistrano/cli/execute.rb:14:in `execute'
    from /Users/ajjahn/.rvm/gems/ruby-1.9.3-p392/gems/capistrano-2.15.5/bin/cap:4:in `<top (required)>'
    from /Users/ajjahn/.rvm/gems/ruby-1.9.3-p392/bin/cap:19:in `load'
    from /Users/ajjahn/.rvm/gems/ruby-1.9.3-p392/bin/cap:19:in `<main>'
    from /Users/ajjahn/.rvm/gems/ruby-1.9.3-p392/bin/ruby_noexec_wrapper:14:in `eval'
    from /Users/ajjahn/.rvm/gems/ruby-1.9.3-p392/bin/ruby_noexec_wrapper:14:in `<main>'
```

Here is the task it is called from in deploy.rb (the put method is on line 60 in the file):

```
  task :setup_config, roles: :app do
    sudo "ln -nfs #{current_path}/config/nginx.conf /etc/nginx/conf.d/#{application}.conf"
    sudo "ln -nfs #{current_path}/config/unicorn_init.sh /etc/init.d/unicorn_#{application}"
    run "mkdir -p #{shared_path}/config"
    put "Test String", "#{shared_path}/config/database.yml"
  end
```

Seems as though the `@operation` instance variable isn't being set here: https://github.com/capistrano/capistrano/blob/master/lib/capistrano/transfer.rb#L143

**Comment by ryana** [comment]
@vizcay you ever figure this out? I just ran into it.

**Comment by vizcay** [comment]
@ryana I think so, but I don't remember the exact cause.. I believe it was related to fs permissions..
