### ISSUE TITLE
Deploy fails without SCM (:scm, :none)

### ISSUE THREAD

**Issue by ain** [capistrano/capistrano#777]
As described in this [Google Groups discussion](https://groups.google.com/forum/#!topic/capistrano/0ApwPJk1NWc) there are scenarios where SCM-less deploy may be desired. Currently, with `:scm, :none` a following error is thrown:

``` log
ain$ cap staging deploy --trace
** Invoke staging (first_time)
** Execute staging
** Invoke load:defaults (first_time)
** Execute load:defaults
cap aborted!
cannot load such file -- capistrano/none.rb
/Users/ain/.rvm/gems/ruby-2.0.0-p247/gems/capistrano-3.0.0/lib/capistrano/setup.rb:14:in `load'
/Users/ain/.rvm/gems/ruby-2.0.0-p247/gems/capistrano-3.0.0/lib/capistrano/setup.rb:14:in `block (2 levels) in <top (required)>'
/Users/ain/.rvm/gems/ruby-2.0.0-p247@global/gems/rake-10.1.0/lib/rake/task.rb:236:in `call'
/Users/ain/.rvm/gems/ruby-2.0.0-p247@global/gems/rake-10.1.0/lib/rake/task.rb:236:in `block in execute'
/Users/ain/.rvm/gems/ruby-2.0.0-p247@global/gems/rake-10.1.0/lib/rake/task.rb:231:in `each'
/Users/ain/.rvm/gems/ruby-2.0.0-p247@global/gems/rake-10.1.0/lib/rake/task.rb:231:in `execute'
/Users/ain/.rvm/gems/ruby-2.0.0-p247@global/gems/rake-10.1.0/lib/rake/task.rb:175:in `block in invoke_with_call_chain'
/Users/ain/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/monitor.rb:211:in `mon_synchronize'
/Users/ain/.rvm/gems/ruby-2.0.0-p247@global/gems/rake-10.1.0/lib/rake/task.rb:168:in `invoke_with_call_chain'
/Users/ain/.rvm/gems/ruby-2.0.0-p247@global/gems/rake-10.1.0/lib/rake/task.rb:161:in `invoke'
/Users/ain/.rvm/gems/ruby-2.0.0-p247@global/gems/rake-10.1.0/lib/rake/application.rb:149:in `invoke_task'
/Users/ain/.rvm/gems/ruby-2.0.0-p247@global/gems/rake-10.1.0/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/Users/ain/.rvm/gems/ruby-2.0.0-p247@global/gems/rake-10.1.0/lib/rake/application.rb:106:in `each'
/Users/ain/.rvm/gems/ruby-2.0.0-p247@global/gems/rake-10.1.0/lib/rake/application.rb:106:in `block in top_level'
/Users/ain/.rvm/gems/ruby-2.0.0-p247@global/gems/rake-10.1.0/lib/rake/application.rb:115:in `run_with_threads'
/Users/ain/.rvm/gems/ruby-2.0.0-p247@global/gems/rake-10.1.0/lib/rake/application.rb:100:in `top_level'
/Users/ain/.rvm/gems/ruby-2.0.0-p247@global/gems/rake-10.1.0/lib/rake/application.rb:78:in `block in run'
/Users/ain/.rvm/gems/ruby-2.0.0-p247@global/gems/rake-10.1.0/lib/rake/application.rb:165:in `standard_exception_handling'
/Users/ain/.rvm/gems/ruby-2.0.0-p247@global/gems/rake-10.1.0/lib/rake/application.rb:75:in `run'
/Users/ain/.rvm/gems/ruby-2.0.0-p247/gems/capistrano-3.0.0/lib/capistrano/application.rb:12:in `run'
/Users/ain/.rvm/gems/ruby-2.0.0-p247/gems/capistrano-3.0.0/bin/cap:3:in `<top (required)>'
/Users/ain/.rvm/gems/ruby-2.0.0-p247/bin/cap:23:in `load'
/Users/ain/.rvm/gems/ruby-2.0.0-p247/bin/cap:23:in `<main>'
/Users/ain/.rvm/gems/ruby-2.0.0-p247/bin/ruby_noexec_wrapper:14:in `eval'
/Users/ain/.rvm/gems/ruby-2.0.0-p247/bin/ruby_noexec_wrapper:14:in `<main>'
Tasks: TOP => staging
```

Any alternatives in Cap 3?

**Comment by nicolas-bastien** [comment]
@ain hello I have the same error as yours in your first post.

Would be great if you can explain me what solution you use to solve your problem
(I read all the comments and other issues but I just fell lost !)

Thanks a lot

**Comment by ain** [comment]
@nicolas-bastien I resorted to handling it with a Bash script on Bamboo. Basically a Capistrano-like structure with a `current` symlink, version folders in `releases/` and GNU `ls` to allow sorting version folders by version with `ls -lv` so you could only keep the last 5 versions.

**Comment by nicolas-bastien** [comment]
@leehambley if I understand well I need to create my own scm : archive.

I found this to have an example https://github.com/ctaintor/capistrano-rails-artifact but it's not exactly what I need.

I still have the error : cannot load such file -- capistrano/archive.rb

So my question is I added this in lib/capistrano how can I declare it to be in the autoloaded path so I don't need to make a plugin ?
(PS sorry I'm a PHP guy who's having hard time with ruby...)

**Comment by leehambley** [comment]
Hi @nicolas-bastien that's pretty much the gist of it indeed. You should just be able to `require_relative ../` from `Capfile` or `deploy.rb` to anywhere for your file to be loaded. If not, ping me back and maybe I can help.
