### ISSUE TITLE
Tasks in other namespaces can't be found if they are later in the deploy.rb file (Cap 3.1.0)

### ISSUE THREAD

**Issue by andytinycat** [capistrano/capistrano#881]
It seems some behaviour changed between Cap 3.0.1 and 3.1.0.

Let's say I have the following in my `deploy.rb`:

```
namespace :deploy do
  desc 'Restart application'
  task :restart do
    on roles(:all) do
      ...some stuff...
    end
  end

  after :finishing, 'deploy:cleanup'
  after :publishing, 'deploy:restart'
  after :updated', 'othernamespace:othertask'
end

namespace :othernamespace
  desc 'something'
  task :othertask do
    ...do something...
  end
end
```

With Capistrano 3.0.1, the hooking of `othernamespace:othertask` after `deploy:update` works perfectly (even though it isn't defined until later in deploy.rb).

If I upgrade to 3.1.0, I get the following trace when trying to do _anything_ with Capistrano using this `deploy.rb`:

```
$ cap production deploy --trace    
** Invoke production (first_time)
** Execute production
** Invoke load:defaults (first_time)
** Execute load:defaults
cap aborted!
Don't know how to build task 'foreman:export'
/Users/andy/.rvm/gems/ruby-2.0.0-p353@myapps/gems/rake-10.0.4/lib/rake/task_manager.rb:49:in `[]'
/Users/andy/.rvm/gems/ruby-2.0.0-p353@myapps/gems/rake-10.0.4/lib/rake/task.rb:339:in `[]'
/Users/andy/.rvm/gems/ruby-2.0.0-p353@myapps/gems/capistrano-3.1.0/lib/capistrano/dsl/task_enhancements.rb:10:in `after'
config/deploy.rb:35:in `block in <top (required)>'
/Users/andy/.rvm/gems/ruby-2.0.0-p353@myapps/gems/rake-10.0.4/lib/rake/task_manager.rb:196:in `in_namespace'
/Users/andy/.rvm/gems/ruby-2.0.0-p353@myapps/gems/rake-10.0.4/lib/rake/dsl_definition.rb:104:in `namespace'
config/deploy.rb:19:in `<top (required)>'
/Users/andy/.rvm/gems/ruby-2.0.0-p353@myapps/gems/capistrano-3.1.0/lib/capistrano/setup.rb:14:in `load'
/Users/andy/.rvm/gems/ruby-2.0.0-p353@myapps/gems/capistrano-3.1.0/lib/capistrano/setup.rb:14:in `block (2 levels) in <top (required)>'
/Users/andy/.rvm/gems/ruby-2.0.0-p353@myapps/gems/rake-10.0.4/lib/rake/task.rb:246:in `call'
/Users/andy/.rvm/gems/ruby-2.0.0-p353@myapps/gems/rake-10.0.4/lib/rake/task.rb:246:in `block in execute'
/Users/andy/.rvm/gems/ruby-2.0.0-p353@myapps/gems/rake-10.0.4/lib/rake/task.rb:241:in `each'
/Users/andy/.rvm/gems/ruby-2.0.0-p353@myapps/gems/rake-10.0.4/lib/rake/task.rb:241:in `execute'
/Users/andy/.rvm/gems/ruby-2.0.0-p353@myapps/gems/rake-10.0.4/lib/rake/task.rb:184:in `block in invoke_with_call_chain'
/Users/andy/.rvm/rubies/ruby-2.0.0-p353/lib/ruby/2.0.0/monitor.rb:211:in `mon_synchronize'
/Users/andy/.rvm/gems/ruby-2.0.0-p353@myapps/gems/rake-10.0.4/lib/rake/task.rb:177:in `invoke_with_call_chain'
/Users/andy/.rvm/gems/ruby-2.0.0-p353@myapps/gems/rake-10.0.4/lib/rake/task.rb:170:in `invoke'
/Users/andy/.rvm/gems/ruby-2.0.0-p353@myapps/gems/rake-10.0.4/lib/rake/application.rb:143:in `invoke_task'
/Users/andy/.rvm/gems/ruby-2.0.0-p353@myapps/gems/rake-10.0.4/lib/rake/application.rb:101:in `block (2 levels) in top_level'
/Users/andy/.rvm/gems/ruby-2.0.0-p353@myapps/gems/rake-10.0.4/lib/rake/application.rb:101:in `each'
/Users/andy/.rvm/gems/ruby-2.0.0-p353@myapps/gems/rake-10.0.4/lib/rake/application.rb:101:in `block in top_level'
/Users/andy/.rvm/gems/ruby-2.0.0-p353@myapps/gems/rake-10.0.4/lib/rake/application.rb:110:in `run_with_threads'
/Users/andy/.rvm/gems/ruby-2.0.0-p353@myapps/gems/rake-10.0.4/lib/rake/application.rb:95:in `top_level'
/Users/andy/.rvm/gems/ruby-2.0.0-p353@myapps/gems/rake-10.0.4/lib/rake/application.rb:73:in `block in run'
/Users/andy/.rvm/gems/ruby-2.0.0-p353@myapps/gems/rake-10.0.4/lib/rake/application.rb:160:in `standard_exception_handling'
/Users/andy/.rvm/gems/ruby-2.0.0-p353@myapps/gems/rake-10.0.4/lib/rake/application.rb:70:in `run'
/Users/andy/.rvm/gems/ruby-2.0.0-p353@myapps/gems/capistrano-3.1.0/lib/capistrano/application.rb:15:in `run'
/Users/andy/.rvm/gems/ruby-2.0.0-p353@myapps/gems/capistrano-3.1.0/bin/cap:3:in `<top (required)>'
/Users/andy/.rvm/gems/ruby-2.0.0-p353@myapps/bin/cap:23:in `load'
/Users/andy/.rvm/gems/ruby-2.0.0-p353@myapps/bin/cap:23:in `<main>'
/Users/andy/.rvm/gems/ruby-2.0.0-p353@myapps/bin/ruby_executable_hooks:15:in `eval'
/Users/andy/.rvm/gems/ruby-2.0.0-p353@myapps/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => production
```

If I switch the namespace ordering (so that `othernamespace` is above `deploy` in the file) both Cap 3.0.1 and 3.1.0 are happy and will deploy.

Is this a bug, or by design? I didn't notice anything in the changelog about this change.

**Comment by ifokeev** [comment]
Fixed in master now
https://github.com/capistrano/capistrano/commit/5fcf3da44424975e098a4fe860fe961c0102e22d

**Comment by fguillen** [comment]
Still on `3.4.0`
